const COLLEGE_TEAMS = {
  'Georgia':       { color: '#BA0C2F', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png' },
  'Michigan':      { color: '#00274C', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png' },
  'Ohio State':    { color: '#BB0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png' },
  'Alabama':       { color: '#9E1B32', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png' },
  'Notre Dame':    { color: '#0C2340', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png' },
  'Texas Tech':    { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png' },
  'Tennessee':     { color: '#FF8200', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png' },
  'Illinois':      { color: '#E84A27', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png' },
  'Arizona State': { color: '#8C1D40', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png' },
  'San Diego State': { color: '#A6192E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png' },
  'South Carolina': { color: '#73000a', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png' },
  'Miami':         { color: '#F47321', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png' },
  'Indiana':       { color: '#990000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png' },
  'LSU':           { color: '#461D7C', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png' },
  'USC':           { color: '#990000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png' },
  'Oregon':        { color: '#124734', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png' },
  'Penn State':    { color: '#041E42', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png' },
  'Utah':          { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png' },
  'Toledo':        { color: '#154733', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png' },
  'Clemson':       { color: '#F56600', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png' },
  'Washington':    { color: '#4B2E83', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png' },
  'Auburn':        { color: '#0C2340', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png' },
  'Missouri':      { color: '#2C2A29', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png' },
  'Texas A&M':     { color: '#500000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png' },
  'Florida':       { color: '#0021A5', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png' },
  'Texas':         { color: '#BF5700', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png' },
  'Vanderbilt':    { color: '#866D4B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png' },
  'Iowa':          { color: '#FFCD00', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png' },
  'UCF':           { color: '#BA9B37', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png' },
  'Cincinnati':    { color: '#E00122', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png' },
  'Georgia Tech':  { color: '#B3A369', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png' },
  'Ole Miss':      { color: '#CE1126', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png' },
  'Arkansas':      { color: '#9D2235', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png' },
  'Arizona':       { color: '#003366', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png' },
  'Georgia State': { color: '#0039A6', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2859.png' },
  'UConn':         { color: '#000E2F', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png' },
  'Iowa State':    { color: '#C8102E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png' },
  'Stanford':      { color: '#8C1515', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png' },
  'Northwestern':  { color: '#4E2A84', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png' },
  'TCU':           { color: '#4D1979', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png' },
  'Pittsburgh':    { color: '#003594', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png' },
  'NC State':      { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png' },
  'North Dakota St': { color: '#005643', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png' },
  'Duke':          { color: '#003087', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png' },
  'Florida State': { color: '#78243C', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png' },
  'Kentucky':      { color: '#0033A0', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png' },
  'Kansas State':  { color: '#512888', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png' },
  'Nebraska':      { color: '#E4173E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png' },
  'Boston College': { color: '#80162B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png' },
  'Wake Forest':   { color: '#9E7E38', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png' },
  'Virginia':      { color: '#232D4B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png' },
  'Boise State':   { color: '#0033A0', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png' },
  'SFA':           { color: '#32174D', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2617.png' },
  'Mississippi St':{ color: '#660000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png' },
  'Baylor':        { color: '#154734', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png' },
  'Michigan State': { color: '#18453B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png' },
  'California':    { color: '#003262', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png' },
  'SMU':           { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png' },
  'Memphis':       { color: '#003087', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png' },
  'Oklahoma':        { color: '#841617', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png' },
  'Georgia State':   { color: '#0039A6', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/290.png' },
  'Louisville':      { color: '#AD0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png' },
};

const NFL_TEAMS = {
  TEN: { name: 'Tennessee Titans',       abbr: 'TEN', color: '#4B92DB' },
  CLE: { name: 'Cleveland Browns',       abbr: 'CLE', color: '#FF3C00' },
  NYG: { name: 'New York Giants',        abbr: 'NYG', color: '#0B2265' },
  NE:  { name: 'New England Patriots',   abbr: 'NE',  color: '#002244' },
  JAX: { name: 'Jacksonville Jaguars',   abbr: 'JAX', color: '#006778' },
  LV:  { name: 'Las Vegas Raiders',      abbr: 'LV',  color: '#A5ACAF' },
  NYJ: { name: 'New York Jets',          abbr: 'NYJ', color: '#125740' },
  CAR: { name: 'Carolina Panthers',      abbr: 'CAR', color: '#0085CA' },
  NO:  { name: 'New Orleans Saints',     abbr: 'NO',  color: '#D3BC8D' },
  CHI: { name: 'Chicago Bears',          abbr: 'CHI', color: '#0B162A' },
  SF:  { name: 'San Francisco 49ers',    abbr: 'SF',  color: '#AA0000' },
  DAL: { name: 'Dallas Cowboys',         abbr: 'DAL', color: '#003594' },
  MIA: { name: 'Miami Dolphins',         abbr: 'MIA', color: '#008E97' },
  IND: { name: 'Indianapolis Colts',     abbr: 'IND', color: '#002C5F' },
  ATL: { name: 'Atlanta Falcons',        abbr: 'ATL', color: '#A71930' },
  ARI: { name: 'Arizona Cardinals',      abbr: 'ARI', color: '#97233F' },
  CIN: { name: 'Cincinnati Bengals',     abbr: 'CIN', color: '#FB4F14' },
  SEA: { name: 'Seattle Seahawks',       abbr: 'SEA', color: '#002244' },
  TB:  { name: 'Tampa Bay Buccaneers',   abbr: 'TB',  color: '#D50A0A' },
  DEN: { name: 'Denver Broncos',         abbr: 'DEN', color: '#FB4F14' },
  PIT: { name: 'Pittsburgh Steelers',    abbr: 'PIT', color: '#FFB612' },
  LAC: { name: 'Los Angeles Chargers',   abbr: 'LAC', color: '#0080C6' },
  GB:  { name: 'Green Bay Packers',      abbr: 'GB',  color: '#203731' },
  MIN: { name: 'Minnesota Vikings',      abbr: 'MIN', color: '#4F2683' },
  HOU: { name: 'Houston Texans',         abbr: 'HOU', color: '#03202F' },
  LAR: { name: 'Los Angeles Rams',       abbr: 'LAR', color: '#003594' },
  BAL: { name: 'Baltimore Ravens',       abbr: 'BAL', color: '#241773' },
  WAS: { name: 'Washington Commanders',  abbr: 'WAS', color: '#5A1414' },
  DET: { name: 'Detroit Lions',          abbr: 'DET', color: '#0076B6' },
  BUF: { name: 'Buffalo Bills',          abbr: 'BUF', color: '#00338D' },
  PHI: { name: 'Philadelphia Eagles',    abbr: 'PHI', color: '#004C54' },
  KC:  { name: 'Kansas City Chiefs',     abbr: 'KC',  color: '#E31837' },
};

const NFL_DRAFT_ORDER = [
  { pick: 1,  team: 'LV',  needs: ['QB', 'WR', 'OT', 'DL'], note: 'Raiders on the clock for Mendoza?' },
  { pick: 2,  team: 'NYJ', needs: ['LB', 'WR', 'EDGE', 'CB'], note: '' },
  { pick: 3,  team: 'ARI', needs: ['OT', 'EDGE', 'QB', 'LB'], note: 'Kyler Murray departed this offseason' },
  { pick: 4,  team: 'TEN', needs: ['RB', 'EDGE', 'LB', 'WR'], note: 'Protecting Cam Ward is priority #1' },
  { pick: 5,  team: 'NYG', needs: ['LB', 'S', 'WR', 'RB'], note: 'Who is going to replace Sexy Dexy?' },
  { pick: 6,  team: 'CLE', needs: ['WR', 'OT', 'CB', 'EDGE'], note: '' },
  { pick: 7,  team: 'WAS', needs: ['EDGE', 'S', 'WR', 'RB'], note: '' },
  { pick: 8,  team: 'NO',  needs: ['WR', 'EDGE', 'CB', 'LB'], note: '' },
  { pick: 9,  team: 'KC',  needs: ['CB', 'EDGE', 'WR', 'OT'], note: 'Rare top-10 pick for the Chiefs' },
  { pick: 10, team: 'NYG', needs: ['LB', 'S', 'WR', 'RB'], note: '' },
  { pick: 11, team: 'MIA', needs: ['CB', 'WR', 'OT', 'EDGE'], note: 'Tua Tagovailoa departed in FA' },
  { pick: 12, team: 'DAL', needs: ['CB', 'EDGE', 'LB', 'S'], note: 'Post-Micah Parsons era begins' },
  { pick: 13, team: 'LAR', needs: ['WR', 'OT', 'LB', 'CB'], note: 'via ATL' },
  { pick: 14, team: 'BAL', needs: ['IOL', 'WR', 'TE', 'OT'], note: '' },
  { pick: 15, team: 'TB',  needs: ['EDGE', 'TE', 'LB', 'CB'], note: '' },
  { pick: 16, team: 'NYJ', needs: ['LB', 'WR', 'EDGE', 'CB'], note: 'via IND' },
  { pick: 17, team: 'DET', needs: ['OT', 'EDGE', 'DL', 'CB'], note: '' },
  { pick: 18, team: 'MIN', needs: ['S', 'DL', 'CB', 'RB'], note: '' },
  { pick: 19, team: 'CAR', needs: ['TE', 'WR', 'OT', 'CB'], note: '' },
  { pick: 20, team: 'DAL', needs: ['CB', 'EDGE', 'LB', 'S'], note: 'via GB' },
  { pick: 21, team: 'PIT', needs: ['WR', 'OT', 'IOL', 'QB'], note: 'Drafting in their home city' },
  { pick: 22, team: 'LAC', needs: ['EDGE', 'IOL', 'DL', 'OT'], note: '' },
  { pick: 23, team: 'PHI', needs: ['OT', 'EDGE', 'WR', 'TE'], note: '' },
  { pick: 24, team: 'CLE', needs: ['WR', 'OT', 'CB', 'EDGE'], note: 'via JAX' },
  { pick: 25, team: 'CHI', needs: ['DL', 'EDGE', 'S', 'IOL'], note: '' },
  { pick: 26, team: 'BUF', needs: ['EDGE', 'WR', 'LB', 'DL'], note: '' },
  { pick: 27, team: 'SF',  needs: ['OT', 'EDGE', 'WR', 'DL'], note: '' },
  { pick: 28, team: 'HOU', needs: ['DL', 'OT', 'IOL', 'LB'], note: '' },
  { pick: 29, team: 'KC',  needs: ['CB', 'EDGE', 'WR', 'OT'], note: 'via LAR' },
  { pick: 30, team: 'MIA', needs: ['CB', 'WR', 'OT', 'EDGE'], note: 'via DEN' },
  { pick: 31, team: 'NE',  needs: ['EDGE', 'OT', 'WR', 'LB'], note: '' },
  { pick: 32, team: 'SEA', needs: ['CB', 'RB', 'EDGE', 'IOL'], note: '' },
];

const NFL_PROSPECTS = [
  { rank: 1,  name: 'Arvell Reese',         pos: 'LB',   school: 'Ohio State',      note: '' },
  { rank: 2,  name: 'Fernando Mendoza',     pos: 'QB',   school: 'Indiana',         note: '' },
  { rank: 3,  name: 'David Bailey',         pos: 'EDGE', school: 'Texas Tech',      note: '' },
  { rank: 4,  name: 'Jeremiyah Love',       pos: 'RB',   school: 'Notre Dame',      note: '' },
  { rank: 5,  name: 'Francis Mauigoa',      pos: 'OT',   school: 'Miami',           note: '' },
  { rank: 6,  name: 'Caleb Downs',          pos: 'S',    school: 'Ohio State',      note: '' },
  { rank: 7,  name: 'Sonny Styles',         pos: 'LB',   school: 'Ohio State',      note: '' },
  { rank: 8,  name: 'Mansoor Delane',       pos: 'CB',   school: 'LSU',             note: '' },
  { rank: 9,  name: 'Rueben Bain Jr.',      pos: 'EDGE', school: 'Miami',           note: '' },
  { rank: 10, name: 'Makai Lemon',          pos: 'WR',   school: 'USC',             note: '' },
  { rank: 11, name: 'Kenyon Sadiq',         pos: 'TE',   school: 'Oregon',          note: '' },
  { rank: 12, name: 'Jordyn Tyson',         pos: 'WR',   school: 'Arizona State',   note: '' },
  { rank: 13, name: 'Carnell Tate',         pos: 'WR',   school: 'Ohio State',      note: '' },
  { rank: 14, name: 'Monroe Freeling',      pos: 'OT',   school: 'Georgia',         note: '' },
  { rank: 15, name: 'Olaivavega Ioane',     pos: 'OG',   school: 'Penn State',      note: '' },
  { rank: 16, name: 'Jermod McCoy',         pos: 'CB',   school: 'Tennessee',       note: '' },
  { rank: 17, name: 'Kadyn Proctor',        pos: 'OT',   school: 'Alabama',         note: '' },
  { rank: 18, name: 'Akheem Mesidor',       pos: 'EDGE', school: 'Miami',           note: '' },
  { rank: 19, name: 'Spencer Fano',         pos: 'OT',   school: 'Utah',            note: '' },
  { rank: 20, name: 'Dillon Thieneman',     pos: 'S',    school: 'Oregon',          note: '' },
  { rank: 21, name: 'Emmanuel McNeil-Warren', pos: 'S',  school: 'Toledo',          note: '' },
  { rank: 22, name: 'Avieon Terrell',       pos: 'CB',   school: 'Clemson',         note: '' },
  { rank: 23, name: 'Denzel Boston',        pos: 'WR',   school: 'Washington',      note: '' },
  { rank: 24, name: 'Omar Cooper Jr.',      pos: 'WR',   school: 'Indiana',         note: '' },
  { rank: 25, name: 'Keldric Faulk',        pos: 'EDGE', school: 'Auburn',          note: '' },
  { rank: 26, name: 'Kayden McDonald',      pos: 'DT',   school: 'Ohio State',      note: '' },
  { rank: 27, name: 'Peter Woods',          pos: 'DT',   school: 'Clemson',         note: '' },
  { rank: 28, name: 'Caleb Lomu',           pos: 'OT',   school: 'Utah',            note: '' },
  { rank: 29, name: 'Zion Young',           pos: 'EDGE', school: 'Missouri',        note: '' },
  { rank: 30, name: 'Cashius Howell',       pos: 'EDGE', school: 'Texas A&M',       note: '' },
  { rank: 31, name: 'Colton Hood',          pos: 'CB',   school: 'Tennessee',       note: '' },
  { rank: 32, name: 'KC Concepcion',        pos: 'WR',   school: 'Texas A&M',       note: '' },
  { rank: 33, name: 'Chase Bisontis',       pos: 'OG',   school: 'Texas A&M',       note: '' },
  { rank: 34, name: 'Caleb Banks',          pos: 'DT',   school: 'Florida',         note: '' },
  { rank: 35, name: 'Anthony Hill Jr.',     pos: 'LB',   school: 'Texas',           note: '' },
  { rank: 36, name: 'Eli Stowers',          pos: 'TE',   school: 'Vanderbilt',      note: '' },
  { rank: 37, name: 'Ty Simpson',           pos: 'QB',   school: 'Alabama',         note: '' },
  { rank: 38, name: 'Brandon Cisse',        pos: 'CB',   school: 'South Carolina',  note: '' },
  { rank: 39, name: 'Chris Johnson',        pos: 'CB',   school: 'San Diego State', note: '' },
  { rank: 40, name: 'Zachariah Branch',     pos: 'WR',   school: 'Georgia',         note: '' },
  { rank: 41, name: 'Max Iheanachor',       pos: 'OT',   school: 'Arizona State',   note: '' },
  { rank: 42, name: 'Chris Brazzell II',    pos: 'WR',   school: 'Tennessee',       note: '' },
  { rank: 43, name: 'Germie Bernard',       pos: 'WR',   school: 'Alabama',         note: '' },
  { rank: 44, name: 'Gabe Jacas',           pos: 'EDGE', school: 'Illinois',        note: '' },
  { rank: 45, name: 'CJ Allen',             pos: 'LB',   school: 'Georgia',         note: '' },
  { rank: 46, name: 'Jacob Rodriguez',      pos: 'LB',   school: 'Texas Tech',      note: '' },
  { rank: 47, name: 'Emmanuel Pregnon',     pos: 'OG',   school: 'Oregon',          note: '' },
  { rank: 48, name: 'Keionte Scott',        pos: 'CB',   school: 'Miami',           note: '' },
  { rank: 49, name: 'Christen Miller',      pos: 'DT',   school: 'Georgia',         note: '' },
  { rank: 50, name: 'Jadarian Price',       pos: 'RB',   school: 'Notre Dame',      note: '' },
  { rank: 51,  name: 'Gennings Dunker',        pos: 'OT',   school: 'Iowa',            note: '' },
  { rank: 52,  name: 'Blake Miller',           pos: 'OT',   school: 'Clemson',         note: '' },
  { rank: 53,  name: 'T.J. Parker',            pos: 'EDGE', school: 'Clemson',         note: '' },
  { rank: 54,  name: 'Malachi Lawrence',       pos: 'EDGE', school: 'UCF',             note: '' },
  { rank: 55,  name: 'Jake Golday',            pos: 'LB',   school: 'Cincinnati',      note: '' },
  { rank: 56,  name: 'A.J. Haulcy',            pos: 'S',    school: 'LSU',             note: '' },
  { rank: 57,  name: 'Antonio Williams',       pos: 'WR',   school: 'Clemson',         note: '' },
  { rank: 58,  name: 'Keylan Rutledge',        pos: 'OG',   school: 'Georgia Tech',    note: '' },
  { rank: 59,  name: 'Malachi Fields',         pos: 'WR',   school: 'Notre Dame',      note: '' },
  { rank: 60,  name: 'Derrick Moore',          pos: 'EDGE', school: 'Michigan',        note: '' },
  { rank: 61,  name: 'R Mason Thomas',         pos: 'EDGE', school: 'Oklahoma',        note: '' },
  { rank: 62,  name: 'Josiah Trotter',         pos: 'LB',   school: 'Missouri',        note: '' },
  { rank: 63,  name: 'Zxavian Harris',         pos: 'DT',   school: 'Ole Miss',        note: '' },
  { rank: 64,  name: 'Max Klare',              pos: 'TE',   school: 'Ohio State',      note: '' },
  { rank: 65,  name: 'Malik Muhammad',         pos: 'CB',   school: 'Texas',           note: '' },
  { rank: 66,  name: 'D\'Angelo Ponds',        pos: 'CB',   school: 'Indiana',         note: '' },
  { rank: 67,  name: 'Lee Hunter',             pos: 'DT',   school: 'Texas Tech',      note: '' },
  { rank: 68,  name: 'Mike Washington Jr.',    pos: 'RB',   school: 'Arkansas',        note: '' },
  { rank: 69,  name: 'Treydan Stukes',         pos: 'S',    school: 'Arizona',         note: '' },
  { rank: 70,  name: 'Ted Hurst',              pos: 'WR',   school: 'Georgia State',   note: '' },
  { rank: 71,  name: 'Jalon Kilgore',          pos: 'S',    school: 'South Carolina',  note: '' },
  { rank: 72,  name: 'Skyler Bell',            pos: 'WR',   school: 'UConn',           note: '' },
  { rank: 73,  name: 'Elijah Sarratt',         pos: 'WR',   school: 'Indiana',         note: '' },
  { rank: 74,  name: 'Keyron Crawford',        pos: 'EDGE', school: 'Auburn',          note: '' },
  { rank: 75,  name: 'Keith Abney II',         pos: 'CB',   school: 'Arizona State',   note: '' },
  { rank: 76,  name: 'De\'Zhaun Stribling',    pos: 'WR',   school: 'Ole Miss',        note: '' },
  { rank: 77,  name: 'Chris Bell',             pos: 'WR',   school: 'Louisville',      note: '' },
  { rank: 78,  name: 'Domonique Orange',       pos: 'DT',   school: 'Iowa State',      note: '' },
  { rank: 79,  name: 'Jake Slaughter',         pos: 'C',    school: 'Florida',         note: '' },
  { rank: 80,  name: 'Sam Hecht',              pos: 'C',    school: 'Kansas State',    note: '' },
  { rank: 81,  name: 'Deion Burks',            pos: 'WR',   school: 'Oklahoma',        note: '' },
  { rank: 82,  name: 'Zakee Wheatley',         pos: 'S',    school: 'Penn State',      note: '' },
  { rank: 83,  name: 'Sam Roush',              pos: 'TE',   school: 'Stanford',        note: '' },
  { rank: 84,  name: 'Caleb Tiernan',          pos: 'OT',   school: 'Northwestern',    note: '' },
  { rank: 85,  name: 'Bud Clark',              pos: 'S',    school: 'TCU',             note: '' },
  { rank: 86,  name: 'Dametrious Crownover',   pos: 'OT',   school: 'Texas A&M',       note: '' },
  { rank: 87,  name: 'Garrett Nussmeier',      pos: 'QB',   school: 'LSU',             note: '' },
  { rank: 88,  name: 'Jaishawn Barham',        pos: 'EDGE', school: 'Michigan',        note: '' },
  { rank: 89,  name: 'Kyle Louis',             pos: 'LB',   school: 'Pittsburgh',      note: '' },
  { rank: 90,  name: 'Ja\'Kobi Lane',          pos: 'WR',   school: 'USC',             note: '' },
  { rank: 91,  name: 'Davison Igbinosun',      pos: 'CB',   school: 'Ohio State',      note: '' },
  { rank: 92,  name: 'Justin Joly',            pos: 'TE',   school: 'NC State',        note: '' },
  { rank: 93,  name: 'Gracen Halton',          pos: 'DT',   school: 'Oklahoma',        note: '' },
  { rank: 94,  name: 'Joshua Josephs',         pos: 'EDGE', school: 'Tennessee',       note: '' },
  { rank: 95,  name: 'Bryce Lance',            pos: 'WR',   school: 'North Dakota St', note: '' },
  { rank: 96,  name: 'Dani Dennis-Sutton',     pos: 'EDGE', school: 'Penn State',      note: '' },
  { rank: 97,  name: 'Genesis Smith',          pos: 'S',    school: 'Arizona',         note: '' },
  { rank: 98,  name: 'Kamari Ramsey',          pos: 'S',    school: 'USC',             note: '' },
  { rank: 99,  name: 'Logan Jones',            pos: 'C',    school: 'Iowa',            note: '' },
  { rank: 100, name: 'Romello Height',         pos: 'EDGE', school: 'Texas Tech',      note: '' },
  { rank: 101, name: 'LT Overton',             pos: 'EDGE', school: 'Alabama',         note: '' },
  { rank: 102, name: 'Brian Parker II',        pos: 'OG',   school: 'Duke',            note: '' },
  { rank: 103, name: 'Deontae Lawson',         pos: 'LB',   school: 'Alabama',         note: '' },
  { rank: 104, name: 'Connor Lew',             pos: 'C',    school: 'Auburn',          note: '' },
  { rank: 105, name: 'Will Lee III',           pos: 'CB',   school: 'Texas A&M',       note: '' },
  { rank: 106, name: 'Trey Zuhn III',          pos: 'C',    school: 'Texas A&M',       note: '' },
  { rank: 107, name: 'Harold Perkins Jr.',     pos: 'LB',   school: 'LSU',             note: '' },
  { rank: 108, name: 'Darrell Jackson Jr.',    pos: 'DT',   school: 'Florida State',   note: '' },
  { rank: 109, name: 'Chris McClellan',        pos: 'DT',   school: 'Missouri',        note: '' },
  { rank: 110, name: 'Oscar Delp',             pos: 'TE',   school: 'Georgia',         note: '' },
  { rank: 111, name: 'Tyler Onyedim',          pos: 'DT',   school: 'Texas A&M',       note: '' },
  { rank: 112, name: 'Daylen Everette',        pos: 'CB',   school: 'Georgia',         note: '' },
  { rank: 113, name: 'Carson Beck',            pos: 'QB',   school: 'Miami',           note: '' },
  { rank: 114, name: 'Anez Cooper',            pos: 'OG',   school: 'Miami',           note: '' },
  { rank: 115, name: 'Tacario Davis',          pos: 'CB',   school: 'Washington',      note: '' },
  { rank: 116, name: 'Drew Shelton',           pos: 'OT',   school: 'Penn State',      note: '' },
  { rank: 117, name: 'Jack Endries',           pos: 'TE',   school: 'Texas',           note: '' },
  { rank: 118, name: 'Eli Raridon',            pos: 'TE',   school: 'Notre Dame',      note: '' },
  { rank: 119, name: 'Devin Moore',            pos: 'CB',   school: 'Florida',         note: '' },
  { rank: 120, name: 'Austin Barber',          pos: 'OT',   school: 'Florida',         note: '' },
  { rank: 121, name: 'Nicholas Singleton',     pos: 'RB',   school: 'Penn State',      note: '' },
  { rank: 122, name: 'DeMonte Capehart',       pos: 'DT',   school: 'Clemson',         note: '' },
  { rank: 123, name: 'Jalen Farmer',           pos: 'OG',   school: 'Kentucky',        note: '' },
  { rank: 124, name: 'VJ Payne',               pos: 'S',    school: 'Kansas State',    note: '' },
  { rank: 125, name: 'Emmett Johnson',         pos: 'RB',   school: 'Nebraska',        note: '' },
  { rank: 126, name: 'Keagen Trost',           pos: 'OT',   school: 'Missouri',        note: '' },
  { rank: 127, name: 'Jadon Canady',           pos: 'S',    school: 'Oregon',          note: '' },
  { rank: 128, name: 'Chandler Rivers',        pos: 'CB',   school: 'Duke',            note: '' },
  { rank: 129, name: 'Drew Allar',             pos: 'QB',   school: 'Penn State',      note: '' },
  { rank: 130, name: 'Joe Royer',              pos: 'TE',   school: 'Cincinnati',      note: '' },
  { rank: 131, name: 'Jude Bowry',             pos: 'OT',   school: 'Boston College',  note: '' },
  { rank: 132, name: 'Rayshaun Benny',         pos: 'DT',   school: 'Michigan',        note: '' },
  { rank: 133, name: 'Demond Claiborne',       pos: 'RB',   school: 'Wake Forest',     note: '' },
  { rank: 134, name: 'Albert Regis',           pos: 'DT',   school: 'Texas A&M',       note: '' },
  { rank: 135, name: 'Adam Randall',           pos: 'RB',   school: 'Clemson',         note: '' },
  { rank: 136, name: 'J\'Mari Taylor',         pos: 'RB',   school: 'Virginia',        note: '' },
  { rank: 137, name: 'Billy Schrauth',         pos: 'OG',   school: 'Notre Dame',      note: '' },
  { rank: 138, name: 'Kevin Coleman Jr.',      pos: 'WR',   school: 'Missouri',        note: '' },
  { rank: 139, name: 'Kage Casey',             pos: 'OT',   school: 'Boise State',     note: '' },
  { rank: 140, name: 'Jeremiah Wright',        pos: 'OG',   school: 'Auburn',          note: '' },
  { rank: 141, name: 'Charles Demmings',       pos: 'CB',   school: 'SFA',             note: '' },
  { rank: 142, name: 'Jakobe Thomas',          pos: 'S',    school: 'Miami',           note: '' },
  { rank: 143, name: 'Le\'Veon Moss',          pos: 'RB',   school: 'Texas A&M',       note: '' },
  { rank: 144, name: 'Brenen Thompson',        pos: 'WR',   school: 'Mississippi St',  note: '' },
  { rank: 145, name: 'Jeff Caldwell',          pos: 'WR',   school: 'Cincinnati',      note: '' },
  { rank: 146, name: 'Kaytron Allen',          pos: 'RB',   school: 'Penn State',      note: '' },
  { rank: 147, name: 'Zane Durant',            pos: 'DT',   school: 'Penn State',      note: '' },
  { rank: 148, name: 'Michael Trigg',          pos: 'TE',   school: 'Baylor',          note: '' },
  { rank: 149, name: 'Kaleb Elarms-Orr',       pos: 'LB',   school: 'TCU',             note: '' },
  { rank: 150, name: 'Trey Moore',             pos: 'EDGE', school: 'Texas',           note: '' },
  { rank: 151, name: 'Bryce Boettcher',        pos: 'LB',   school: 'Oregon',          note: '' },
  { rank: 152, name: 'Taylen Green',           pos: 'QB',   school: 'Arkansas',        note: '' },
  { rank: 153, name: 'Cole Payton',            pos: 'QB',   school: 'North Dakota St', note: '' },
  { rank: 154, name: 'Josh Cuevas',            pos: 'TE',   school: 'Alabama',         note: '' },
  { rank: 155, name: 'Will Kacmarek',          pos: 'TE',   school: 'Ohio State',      note: '' },
  { rank: 156, name: 'Parker Brailsford',      pos: 'C',    school: 'Alabama',         note: '' },
  { rank: 157, name: 'Matt Gulbin',            pos: 'C',    school: 'Michigan State',  note: '' },
  { rank: 158, name: 'Ephesians Prysock',      pos: 'CB',   school: 'Washington',      note: '' },
  { rank: 159, name: 'Nate Boerkircher',       pos: 'TE',   school: 'Texas A&M',       note: '' },
  { rank: 160, name: 'Jimmy Rolder',           pos: 'LB',   school: 'Michigan',        note: '' },
  { rank: 161, name: 'Alex Harkey',            pos: 'OG',   school: 'Oregon',          note: '' },
  { rank: 162, name: 'Domani Jackson',         pos: 'CB',   school: 'Alabama',         note: '' },
  { rank: 163, name: 'Hezekiah Masses',        pos: 'CB',   school: 'California',      note: '' },
  { rank: 164, name: 'Caden Curry',            pos: 'EDGE', school: 'Ohio State',      note: '' },
  { rank: 165, name: 'Malik Benson',           pos: 'WR',   school: 'Oregon',          note: '' },
  { rank: 166, name: 'George Gumbs Jr.',       pos: 'EDGE', school: 'Florida',         note: '' },
  { rank: 167, name: 'Josh Cameron',           pos: 'WR',   school: 'Baylor',          note: '' },
  { rank: 168, name: 'Isaiah World',           pos: 'OT',   school: 'Oregon',          note: '' },
  { rank: 169, name: 'Julian Neal',            pos: 'CB',   school: 'Arkansas',        note: '' },
  { rank: 170, name: 'Robert Spears-Jennings', pos: 'S',    school: 'Oklahoma',        note: '' },
  { rank: 171, name: 'Bryson Eason',           pos: 'DT',   school: 'Tennessee',       note: '' },
  { rank: 172, name: 'Beau Stephens',          pos: 'OG',   school: 'Iowa',            note: '' },
  { rank: 173, name: 'Riley Nowakowski',       pos: 'TE',   school: 'Indiana',         note: '' },
  { rank: 174, name: 'Michael Taaffe',         pos: 'S',    school: 'Texas',           note: '' },
  { rank: 175, name: 'Jonah Coleman',          pos: 'RB',   school: 'Washington',      note: '' },
  { rank: 176, name: 'Marlin Klein',           pos: 'TE',   school: 'Michigan',        note: '' },
  { rank: 177, name: 'Colbie Young',           pos: 'WR',   school: 'Georgia',         note: '' },
  { rank: 178, name: 'Roman Hemby',            pos: 'RB',   school: 'Indiana',         note: '' },
  { rank: 179, name: 'Logan Fano',             pos: 'EDGE', school: 'Utah',            note: '' },
  { rank: 180, name: 'Matthew Hibner',         pos: 'TE',   school: 'SMU',             note: '' },
  { rank: 181, name: 'Justin Jefferson',       pos: 'LB',   school: 'Alabama',         note: '', espnId: 5150249 },
  { rank: 182, name: 'Seth McGowan',           pos: 'RB',   school: 'Kentucky',        note: '' },
  { rank: 183, name: 'Nick Barrett',           pos: 'DT',   school: 'South Carolina',  note: '' },
  { rank: 184, name: 'Cameron Ball',           pos: 'DT',   school: 'Arkansas',        note: '', espnId: 4691878 },
  { rank: 185, name: 'Travis Burke',           pos: 'OT',   school: 'Memphis',         note: '' },
  { rank: 186, name: 'Markel Bell',            pos: 'OT',   school: 'Miami',           note: '' },
  { rank: 187, name: 'Bishop Fitzgerald',      pos: 'S',    school: 'USC',             note: '' },
  { rank: 188, name: 'Fernando Carmona',       pos: 'OT',   school: 'Arkansas',        note: '' },
  { rank: 189, name: 'Toriano Pride Jr.',      pos: 'CB',   school: 'Missouri',        note: '' },
  { rank: 190, name: 'TJ Hall',                pos: 'CB',   school: 'Iowa',            note: '' },
  { rank: 191, name: 'Caleb Douglas',          pos: 'WR',   school: 'Texas Tech',      note: '' },
  { rank: 192, name: 'Pat Coogan',             pos: 'C',    school: 'Indiana',         note: '' },
  { rank: 193, name: 'J. Michael Sturdivant',  pos: 'WR',   school: 'Florida',         note: '' },
  { rank: 194, name: 'Diego Pounds',           pos: 'OT',   school: 'Ole Miss',        note: '' },
  { rank: 195, name: 'Lander Barton',          pos: 'LB',   school: 'Utah',            note: '' },
  { rank: 196, name: 'Taurean York',           pos: 'LB',   school: 'Texas A&M',       note: '' },
  { rank: 197, name: 'Aiden Fisher',           pos: 'LB',   school: 'Indiana',         note: '' },
  { rank: 198, name: 'Dae\'Quan Wright',       pos: 'TE',   school: 'Ole Miss',        note: '' },
  { rank: 199, name: 'Kendrick Law',           pos: 'WR',   school: 'Kentucky',        note: '' },
  { rank: 200, name: 'Cyrus Allen',            pos: 'WR',   school: 'Cincinnati',      note: '' },
];