const COLLEGE_TEAMS = {
  'Georgia':       { color: '#BA0C2F', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png' },
  'Michigan':      { color: '#00274C', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png' },
  'Ohio State':    { color: '#BB0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png' },
  'Alabama':       { color: '#9E1B32', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png' },
  'Notre Dame':    { color: '#0C2340', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png' },
  'Texas Tech':    { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png' },
  'Tennessee':     { color: '#FF8200', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png' },
  'Illinois':      { color: '#E84A27', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png' },
  'Arizona State': { color: '#8C1D40', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png' },
  'San Diego State': { color: '#A6192E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png' },
  'South Carolina': { color: '#73000a', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png' },
  'Miami':         { color: '#F47321', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png' },
  'Indiana':       { color: '#990000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png' },
  'LSU':           { color: '#461D7C', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png' },
  'USC':           { color: '#990000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png' },
  'Oregon':        { color: '#124734', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png' },
  'Penn State':    { color: '#041E42', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png' },
  'Utah':          { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png' },
  'Toledo':        { color: '#154733', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png' },
  'Clemson':       { color: '#F56600', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png' },
  'Washington':    { color: '#4B2E83', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png' },
  'Auburn':        { color: '#0C2340', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png' },
  'Missouri':      { color: '#2C2A29', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png' },
  'Texas A&M':     { color: '#500000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png' },
  'Florida':       { color: '#0021A5', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png' },
  'Texas':         { color: '#BF5700', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png' },
  'Vanderbilt':    { color: '#866D4B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png' },
  'Iowa':          { color: '#FFCD00', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png' },
  'UCF':           { color: '#BA9B37', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png' },
  'Cincinnati':    { color: '#E00122', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png' },
  'Georgia Tech':  { color: '#B3A369', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png' },
  'Ole Miss':      { color: '#CE1126', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png' },
  'Arkansas':      { color: '#9D2235', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png' },
  'Arizona':       { color: '#003366', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png' },
  'Georgia State': { color: '#0039A6', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2859.png' },
  'UConn':         { color: '#000E2F', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png' },
  'Iowa State':    { color: '#C8102E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png' },
  'Stanford':      { color: '#8C1515', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png' },
  'Northwestern':  { color: '#4E2A84', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png' },
  'TCU':           { color: '#4D1979', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png' },
  'Pittsburgh':    { color: '#003594', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png' },
  'NC State':      { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png' },
  'North Dakota St': { color: '#005643', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png' },
  'Duke':          { color: '#003087', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png' },
  'Florida State': { color: '#78243C', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png' },
  'Kentucky':      { color: '#0033A0', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png' },
  'Kansas State':  { color: '#512888', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png' },
  'Nebraska':      { color: '#E4173E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png' },
  'Boston College': { color: '#80162B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png' },
  'Wake Forest':   { color: '#9E7E38', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png' },
  'Virginia':      { color: '#232D4B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png' },
  'Boise State':   { color: '#0033A0', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png' },
  'SFA':           { color: '#32174D', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2617.png' },
  'Mississippi St':{ color: '#660000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png' },
  'Baylor':        { color: '#154734', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png' },
  'Michigan State': { color: '#18453B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png' },
  'California':    { color: '#003262', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png' },
  'SMU':           { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png' },
  'Memphis':       { color: '#003087', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png' },
  'Oklahoma':        { color: '#841617', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png' },
  'Georgia State':   { color: '#0039A6', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/290.png' },
  'Louisville':      { color: '#AD0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png' },
  'SE Louisiana':   { color: '#542633', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png' },
  'Wisconsin':       { color: '#C5050C', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png' },
  'BYU':             { color: '#002E5D', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png' },
  'BYU':             { color: '#002E5D', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png' },
  'Wyoming':         { color: '#492F24', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png' },
  'Maryland':        { color: '#E03A3E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png' },
  'North Carolina':  { color: '#7BAFD4', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png' },
  'Navy':            { color: '#00205B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png' },
  'App State':       { color: '#222222', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png' },
  'Syracuse':        { color: '#F7641E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png' },
  'Washington State':{ color: '#981E32', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/265.png' },
  'Kansas':          { color: '#0051BA', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png' },
  'Buffalo':         { color: '#005BBB', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png' },
  'Southern Miss':   { color: '#FFAB00', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png' },
  'UTSA':            { color: '#0C2340', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png' },
  'Western Michigan':{ color: '#6C4023', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png' },
  'John Carroll':    { color: '#002C5F', logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2302.png&h=200&w=200' },
  'Oregon State':    { color: '#DC4405', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png' },
  'Houston':         { color: '#C8102E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png' },
  'Ball State':      { color: '#BA0C2F', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png' },
};

const NFL_TEAMS = {
  TEN: { name: 'Tennessee Titans',       abbr: 'TEN', color: '#4B92DB' },
  CLE: { name: 'Cleveland Browns',       abbr: 'CLE', color: '#FF3C00' },
  NYG: { name: 'New York Giants',        abbr: 'NYG', color: '#0B2265' },
  NE:  { name: 'New England Patriots',   abbr: 'NE',  color: '#002244' },
  JAX: { name: 'Jacksonville Jaguars',   abbr: 'JAX', color: '#006778' },
  LV:  { name: 'Las Vegas Raiders',      abbr: 'LV',  color: '#A5ACAF' },
  NYJ: { name: 'New York Jets',          abbr: 'NYJ', color: '#125740' },
  CAR: { name: 'Carolina Panthers',      abbr: 'CAR', color: '#0085CA' },
  NO:  { name: 'New Orleans Saints',     abbr: 'NO',  color: '#D3BC8D' },
  CHI: { name: 'Chicago Bears',          abbr: 'CHI', color: '#0B162A' },
  SF:  { name: 'San Francisco 49ers',    abbr: 'SF',  color: '#AA0000' },
  DAL: { name: 'Dallas Cowboys',         abbr: 'DAL', color: '#003594' },
  MIA: { name: 'Miami Dolphins',         abbr: 'MIA', color: '#008E97' },
  IND: { name: 'Indianapolis Colts',     abbr: 'IND', color: '#002C5F' },
  ATL: { name: 'Atlanta Falcons',        abbr: 'ATL', color: '#A71930' },
  ARI: { name: 'Arizona Cardinals',      abbr: 'ARI', color: '#97233F' },
  CIN: { name: 'Cincinnati Bengals',     abbr: 'CIN', color: '#FB4F14' },
  SEA: { name: 'Seattle Seahawks',       abbr: 'SEA', color: '#002244' },
  TB:  { name: 'Tampa Bay Buccaneers',   abbr: 'TB',  color: '#D50A0A' },
  DEN: { name: 'Denver Broncos',         abbr: 'DEN', color: '#FB4F14' },
  PIT: { name: 'Pittsburgh Steelers',    abbr: 'PIT', color: '#FFB612' },
  LAC: { name: 'Los Angeles Chargers',   abbr: 'LAC', color: '#0080C6' },
  GB:  { name: 'Green Bay Packers',      abbr: 'GB',  color: '#203731' },
  MIN: { name: 'Minnesota Vikings',      abbr: 'MIN', color: '#4F2683' },
  HOU: { name: 'Houston Texans',         abbr: 'HOU', color: '#03202F' },
  LAR: { name: 'Los Angeles Rams',       abbr: 'LAR', color: '#003594' },
  BAL: { name: 'Baltimore Ravens',       abbr: 'BAL', color: '#241773' },
  WAS: { name: 'Washington Commanders',  abbr: 'WAS', color: '#5A1414' },
  DET: { name: 'Detroit Lions',          abbr: 'DET', color: '#0076B6' },
  BUF: { name: 'Buffalo Bills',          abbr: 'BUF', color: '#00338D' },
  PHI: { name: 'Philadelphia Eagles',    abbr: 'PHI', color: '#004C54' },
  KC:  { name: 'Kansas City Chiefs',     abbr: 'KC',  color: '#E31837' },
};

const NFL_DRAFT_ORDER = [
  // ROUND 1
  { pick: 1,  team: 'LV',  round: 1, note: 'Raiders on the clock for Mendoza?' },
  { pick: 2,  team: 'NYJ', round: 1, note: '' },
  { pick: 3,  team: 'ARI', round: 1, note: 'Kyler Murray departed this offseason' },
  { pick: 4,  team: 'TEN', round: 1, note: 'Protecting Cam Ward is priority #1' },
  { pick: 5,  team: 'NYG', round: 1, note: 'Who is going to replace Sexy Dexy?' },
  { pick: 6,  team: 'CLE', round: 1, note: '' },
  { pick: 7,  team: 'WAS', round: 1, note: '' },
  { pick: 8,  team: 'NO',  round: 1, note: '' },
  { pick: 9,  team: 'KC',  round: 1, note: 'Rare top-10 pick for the Chiefs' },
  { pick: 10, team: 'NYG', round: 1, note: '' },
  { pick: 11, team: 'MIA', round: 1, note: 'Tua Tagovailoa departed in FA' },
  { pick: 12, team: 'DAL', round: 1, note: 'Post-Micah Parsons era begins' },
  { pick: 13, team: 'LAR', round: 1, note: 'via ATL' },
  { pick: 14, team: 'BAL', round: 1, note: '' },
  { pick: 15, team: 'TB',  round: 1, note: '' },
  { pick: 16, team: 'NYJ', round: 1, note: 'via IND' },
  { pick: 17, team: 'DET', round: 1, note: '' },
  { pick: 18, team: 'MIN', round: 1, note: '' },
  { pick: 19, team: 'CAR', round: 1, note: '' },
  { pick: 20, team: 'DAL', round: 1, note: 'via GB' },
  { pick: 21, team: 'PIT', round: 1, note: 'Drafting in their home city' },
  { pick: 22, team: 'LAC', round: 1, note: '' },
  { pick: 23, team: 'PHI', round: 1, note: '' },
  { pick: 24, team: 'CLE', round: 1, note: 'via JAX' },
  { pick: 25, team: 'CHI', round: 1, note: '' },
  { pick: 26, team: 'BUF', round: 1, note: '' },
  { pick: 27, team: 'SF',  round: 1, note: '' },
  { pick: 28, team: 'HOU', round: 1, note: '' },
  { pick: 29, team: 'KC',  round: 1, note: 'via LAR' },
  { pick: 30, team: 'MIA', round: 1, note: 'via DEN' },
  { pick: 31, team: 'NE',  round: 1, note: '' },
  { pick: 32, team: 'SEA', round: 1, note: '' },

  // ROUND 2
  { pick: 33, team: 'NYJ', round: 2, note: '' },
  { pick: 34, team: 'ARI', round: 2, note: '' },
  { pick: 35, team: 'TEN', round: 2, note: '' },
  { pick: 36, team: 'LV',  round: 2, note: '' },
  { pick: 37, team: 'NYG', round: 2, note: '' },
  { pick: 38, team: 'HOU', round: 2, note: 'via WSH' },
  { pick: 39, team: 'CLE', round: 2, note: '' },
  { pick: 40, team: 'KC',  round: 2, note: '' },
  { pick: 41, team: 'CIN', round: 2, note: '' },
  { pick: 42, team: 'NO',  round: 2, note: '' },
  { pick: 43, team: 'MIA', round: 2, note: '' },
  { pick: 44, team: 'NYJ', round: 2, note: 'via DAL' },
  { pick: 45, team: 'BAL', round: 2, note: '' },
  { pick: 46, team: 'TB',  round: 2, note: '' },
  { pick: 47, team: 'IND', round: 2, note: '' },
  { pick: 48, team: 'ATL', round: 2, note: '' },
  { pick: 49, team: 'MIN', round: 2, note: '' },
  { pick: 50, team: 'DET', round: 2, note: '' },
  { pick: 51, team: 'CAR', round: 2, note: '' },
  { pick: 52, team: 'GB',  round: 2, note: '' },
  { pick: 53, team: 'PIT', round: 2, note: '' },
  { pick: 54, team: 'PHI', round: 2, note: '' },
  { pick: 55, team: 'LAC', round: 2, note: '' },
  { pick: 56, team: 'JAX', round: 2, note: '' },
  { pick: 57, team: 'CHI', round: 2, note: '' },
  { pick: 58, team: 'SF',  round: 2, note: '' },
  { pick: 59, team: 'HOU', round: 2, note: '' },
  { pick: 60, team: 'CHI', round: 2, note: 'via BUF' },
  { pick: 61, team: 'LAR', round: 2, note: '' },
  { pick: 62, team: 'DEN', round: 2, note: '' },
  { pick: 63, team: 'NE',  round: 2, note: '' },
  { pick: 64, team: 'SEA', round: 2, note: '' },

  // ROUND 3
  { pick: 65, team: 'ARI', round: 3, note: '' },
  { pick: 66, team: 'TEN', round: 3, note: '' },
  { pick: 67, team: 'LV',  round: 3, note: '' },
  { pick: 68, team: 'PHI', round: 3, note: 'via NYJ' },
  { pick: 69, team: 'HOU', round: 3, note: 'via NYG' },
  { pick: 70, team: 'CLE', round: 3, note: '' },
  { pick: 71, team: 'WAS', round: 3, note: '' },
  { pick: 72, team: 'CIN', round: 3, note: '' },
  { pick: 73, team: 'NO',  round: 3, note: '' },
  { pick: 74, team: 'KC',  round: 3, note: '' },
  { pick: 75, team: 'MIA', round: 3, note: '' },
  { pick: 76, team: 'PIT', round: 3, note: 'via DAL' },
  { pick: 77, team: 'TB',  round: 3, note: '' },
  { pick: 78, team: 'IND', round: 3, note: '' },
  { pick: 79, team: 'ATL', round: 3, note: '' },
  { pick: 80, team: 'BAL', round: 3, note: '' },
  { pick: 81, team: 'JAX', round: 3, note: 'via DET' },
  { pick: 82, team: 'MIN', round: 3, note: '' },
  { pick: 83, team: 'CAR', round: 3, note: '' },
  { pick: 84, team: 'GB',  round: 3, note: '' },
  { pick: 85, team: 'PIT', round: 3, note: '' },
  { pick: 86, team: 'LAC', round: 3, note: '' },
  { pick: 87, team: 'MIA', round: 3, note: 'via PHI' },
  { pick: 88, team: 'JAX', round: 3, note: '' },
  { pick: 89, team: 'CHI', round: 3, note: '' },
  { pick: 90, team: 'MIA', round: 3, note: 'via HOU' },
  { pick: 91, team: 'BUF', round: 3, note: '' },
  { pick: 92, team: 'DAL', round: 3, note: 'via SF' },
  { pick: 93, team: 'LAR', round: 3, note: '' },
  { pick: 94, team: 'MIA', round: 3, note: 'via DEN' },
  { pick: 95, team: 'NE',  round: 3, note: '' },
  { pick: 96, team: 'SEA', round: 3, note: '' },
  { pick: 97, team: 'MIN', round: 3, note: '' },
  { pick: 98, team: 'PHI', round: 3, note: '' },
  { pick: 99, team: 'PIT', round: 3, note: '' },
  { pick: 100, team: 'JAX', round: 3, note: 'via DET' },

  // ROUND 4
  { pick: 101, team: 'TEN', round: 4, note: '' },
  { pick: 102, team: 'LV',  round: 4, note: '' },
  { pick: 103, team: 'NYJ', round: 4, note: '' },
  { pick: 104, team: 'ARI', round: 4, note: '' },
  { pick: 105, team: 'NYG', round: 4, note: '' },
  { pick: 106, team: 'HOU', round: 4, note: 'via WSH' },
  { pick: 107, team: 'CLE', round: 4, note: '' },
  { pick: 108, team: 'DEN', round: 4, note: 'via NO' },
  { pick: 109, team: 'KC',  round: 4, note: '' },
  { pick: 110, team: 'CIN', round: 4, note: '' },
  { pick: 111, team: 'DEN', round: 4, note: 'via MIA' },
  { pick: 112, team: 'DAL', round: 4, note: '' },
  { pick: 113, team: 'IND', round: 4, note: '' },
  { pick: 114, team: 'PHI', round: 4, note: 'via ATL' },
  { pick: 115, team: 'BAL', round: 4, note: '' },
  { pick: 116, team: 'TB',  round: 4, note: '' },
  { pick: 117, team: 'LV',  round: 4, note: 'via MIN' },
  { pick: 118, team: 'DET', round: 4, note: '' },
  { pick: 119, team: 'CAR', round: 4, note: '' },
  { pick: 120, team: 'GB',  round: 4, note: '' },
  { pick: 121, team: 'PIT', round: 4, note: '' },
  { pick: 122, team: 'ATL', round: 4, note: 'via PHI' },
  { pick: 123, team: 'LAC', round: 4, note: '' },
  { pick: 124, team: 'JAX', round: 4, note: '' },
  { pick: 125, team: 'NE',  round: 4, note: 'via CHI' },
  { pick: 126, team: 'BUF', round: 4, note: '' },
  { pick: 127, team: 'SF',  round: 4, note: '' },
  { pick: 128, team: 'DET', round: 4, note: 'via HOU' },
  { pick: 129, team: 'CHI', round: 4, note: 'via LAR' },
  { pick: 130, team: 'MIA', round: 4, note: 'via DEN' },
  { pick: 131, team: 'NE',  round: 4, note: '' },
  { pick: 132, team: 'NO',  round: 4, note: 'via SEA' },
  { pick: 133, team: 'SF',  round: 4, note: '' },
  { pick: 134, team: 'LV',  round: 4, note: '' },
  { pick: 135, team: 'PIT', round: 4, note: '' },
  { pick: 136, team: 'NO',  round: 4, note: '' },
  { pick: 137, team: 'PHI', round: 4, note: '' },
  { pick: 138, team: 'SF',  round: 4, note: '' },
  { pick: 139, team: 'SF',  round: 4, note: '' },
  { pick: 140, team: 'NYJ', round: 4, note: '' },

  // ROUND 5
  { pick: 141, team: 'HOU', round: 5, note: 'via LV' },
  { pick: 142, team: 'TEN', round: 5, note: 'via NYJ' },
  { pick: 143, team: 'ARI', round: 5, note: '' },
  { pick: 144, team: 'TEN', round: 5, note: '' },
  { pick: 145, team: 'NYG', round: 5, note: '' },
  { pick: 146, team: 'CLE', round: 5, note: '' },
  { pick: 147, team: 'WAS', round: 5, note: '' },
  { pick: 148, team: 'KC',  round: 5, note: '' },
  { pick: 149, team: 'CLE', round: 5, note: 'via CIN' },
  { pick: 150, team: 'NO',  round: 5, note: '' },
  { pick: 151, team: 'MIA', round: 5, note: '' },
  { pick: 152, team: 'DAL', round: 5, note: '' },
  { pick: 153, team: 'GB',  round: 5, note: 'via ATL' },
  { pick: 154, team: 'BAL', round: 5, note: '' },
  { pick: 155, team: 'TB',  round: 5, note: '' },
  { pick: 156, team: 'IND', round: 5, note: '' },
  { pick: 157, team: 'DET', round: 5, note: '' },
  { pick: 158, team: 'CAR', round: 5, note: 'via MIN' },
  { pick: 159, team: 'CAR', round: 5, note: '' },
  { pick: 160, team: 'GB',  round: 5, note: '' },
  { pick: 161, team: 'PIT', round: 5, note: '' },
  { pick: 162, team: 'BAL', round: 5, note: 'via LAC' },
  { pick: 163, team: 'MIN', round: 5, note: 'via PHI' },
  { pick: 164, team: 'JAX', round: 5, note: '' },
  { pick: 165, team: 'BUF', round: 5, note: 'via CHI' },
  { pick: 166, team: 'JAX', round: 5, note: 'via SF' },
  { pick: 167, team: 'HOU', round: 5, note: '' },
  { pick: 168, team: 'BUF', round: 5, note: '' },
  { pick: 169, team: 'KC',  round: 5, note: 'via LAR' },
  { pick: 170, team: 'DEN', round: 5, note: '' },
  { pick: 171, team: 'NE',  round: 5, note: '' },
  { pick: 172, team: 'NO',  round: 5, note: 'via SEA' },
  { pick: 173, team: 'BAL', round: 5, note: '' },
  { pick: 174, team: 'BAL', round: 5, note: '' },
  { pick: 175, team: 'LV',  round: 5, note: '' },
  { pick: 176, team: 'KC',  round: 5, note: '' },
  { pick: 177, team: 'DAL', round: 5, note: '' },
  { pick: 178, team: 'PHI', round: 5, note: '' },
  { pick: 179, team: 'NYJ', round: 5, note: '' },
  { pick: 180, team: 'DAL', round: 5, note: '' },
  { pick: 181, team: 'DET', round: 5, note: '' },

  // ROUND 6
  { pick: 182, team: 'BUF', round: 6, note: 'via NYJ' },
  { pick: 183, team: 'ARI', round: 6, note: '' },
  { pick: 184, team: 'TEN', round: 6, note: '' },
  { pick: 185, team: 'LV',  round: 6, note: '' },
  { pick: 186, team: 'NYG', round: 6, note: '' },
  { pick: 187, team: 'WAS', round: 6, note: '' },
  { pick: 188, team: 'SEA', round: 6, note: 'via CLE' },
  { pick: 189, team: 'CIN', round: 6, note: '' },
  { pick: 190, team: 'NO',  round: 6, note: '' },
  { pick: 191, team: 'NE',  round: 6, note: 'via KC' },
  { pick: 192, team: 'NYG', round: 6, note: 'via MIA' },
  { pick: 193, team: 'NYG', round: 6, note: 'via DAL' },
  { pick: 194, team: 'TEN', round: 6, note: 'via BAL' },
  { pick: 195, team: 'TB',  round: 6, note: '' },
  { pick: 196, team: 'MIN', round: 6, note: 'via IND' },
  { pick: 197, team: 'PHI', round: 6, note: 'via ATL' },
  { pick: 198, team: 'NE',  round: 6, note: 'via MIN' },
  { pick: 199, team: 'CIN', round: 6, note: 'via DET' },
  { pick: 200, team: 'CAR', round: 6, note: '' },
  { pick: 201, team: 'GB',  round: 6, note: '' },
  { pick: 202, team: 'NE',  round: 6, note: 'via PIT' },
  { pick: 203, team: 'JAX', round: 6, note: 'via PHI' },
  { pick: 204, team: 'LAC', round: 6, note: '' },
  { pick: 205, team: 'DET', round: 6, note: 'via JAX' },
  { pick: 206, team: 'CLE', round: 6, note: 'via CHI' },
  { pick: 207, team: 'LAR', round: 6, note: 'via HOU' },
  { pick: 208, team: 'LV',  round: 6, note: 'via BUF' },
  { pick: 209, team: 'WAS', round: 6, note: 'via SF' },
  { pick: 210, team: 'KC',  round: 6, note: 'via LAR' },
  { pick: 211, team: 'BAL', round: 6, note: 'via DEN' },
  { pick: 212, team: 'NE',  round: 6, note: '' },
  { pick: 213, team: 'DET', round: 6, note: 'via SEA' },
  { pick: 214, team: 'IND', round: 6, note: 'via PIT' },
  { pick: 215, team: 'ATL', round: 6, note: 'via PHI' },
  { pick: 216, team: 'PIT', round: 6, note: '' },

  // ROUND 7
  { pick: 217, team: 'ARI', round: 7, note: '' },
  { pick: 218, team: 'DAL', round: 7, note: 'via TEN' },
  { pick: 219, team: 'LV',  round: 7, note: '' },
  { pick: 220, team: 'BUF', round: 7, note: 'via NYJ' },
  { pick: 221, team: 'CIN', round: 7, note: 'via NYG' },
  { pick: 222, team: 'DET', round: 7, note: 'via CLE' },
  { pick: 223, team: 'WAS', round: 7, note: '' },
  { pick: 224, team: 'PIT', round: 7, note: 'via NO' },
  { pick: 225, team: 'TEN', round: 7, note: 'via KC' },
  { pick: 226, team: 'CIN', round: 7, note: '' },
  { pick: 227, team: 'MIA', round: 7, note: '' },
  { pick: 228, team: 'NYJ', round: 7, note: 'via DAL' },
  { pick: 229, team: 'TB',  round: 7, note: '' },
  { pick: 230, team: 'PIT', round: 7, note: 'via IND' },
  { pick: 231, team: 'ATL', round: 7, note: '' },
  { pick: 232, team: 'LAR', round: 7, note: 'via BAL' },
  { pick: 233, team: 'JAX', round: 7, note: 'via DET' },
  { pick: 234, team: 'MIN', round: 7, note: '' },
  { pick: 235, team: 'MIN', round: 7, note: 'via CAR' },
  { pick: 236, team: 'GB',  round: 7, note: '' },
  { pick: 237, team: 'PIT', round: 7, note: '' },
  { pick: 238, team: 'MIA', round: 7, note: 'via LAC' },
  { pick: 239, team: 'CHI', round: 7, note: 'via PHI' },
  { pick: 240, team: 'JAX', round: 7, note: '' },
  { pick: 241, team: 'CHI', round: 7, note: '' },
  { pick: 242, team: 'NYJ', round: 7, note: 'via BUF' },
  { pick: 243, team: 'HOU', round: 7, note: 'via SF' },
  { pick: 244, team: 'MIN', round: 7, note: 'via HOU' },
  { pick: 245, team: 'JAX', round: 7, note: 'via LAR' },
  { pick: 246, team: 'DEN', round: 7, note: '' },
  { pick: 247, team: 'NE',  round: 7, note: '' },
  { pick: 248, team: 'CLE', round: 7, note: 'via SEA' },
  { pick: 249, team: 'IND', round: 7, note: '' },
  { pick: 250, team: 'BAL', round: 7, note: '' },
  { pick: 251, team: 'LAR', round: 7, note: '' },
  { pick: 252, team: 'LAR', round: 7, note: '' },
  { pick: 253, team: 'BAL', round: 7, note: '' },
  { pick: 254, team: 'IND', round: 7, note: '' },
  { pick: 255, team: 'GB',  round: 7, note: '' },
  { pick: 256, team: 'DEN', round: 7, note: '' },
  { pick: 257, team: 'DEN', round: 7, note: '' },
];

const NFL_TEAM_NEEDS = {
  LV:  ['QB', 'WR', 'OT', 'DL'],
  NYJ: ['LB', 'WR', 'EDGE', 'CB'],
  ARI: ['OT', 'EDGE', 'QB', 'LB'],
  TEN: ['RB', 'EDGE', 'LB', 'WR'],
  NYG: ['LB', 'S', 'WR', 'RB'],
  CLE: ['WR', 'OT', 'CB', 'EDGE'],
  WAS: ['EDGE', 'S', 'WR', 'RB'],
  NO:  ['WR', 'EDGE', 'CB', 'LB'],
  KC:  ['CB', 'EDGE', 'WR', 'OT'],
  CIN: ['CB', 'S', 'EDGE', 'LB'],
  MIA: ['CB', 'WR', 'OT', 'EDGE'],
  DAL: ['CB', 'EDGE', 'LB', 'S'],
  LAR: ['WR', 'OT', 'LB', 'CB'],
  BAL: ['IOL', 'WR', 'TE', 'OT'],
  TB:  ['EDGE', 'TE', 'LB', 'CB'],
  DET: ['OT', 'EDGE', 'DL', 'CB'],
  MIN: ['S', 'DL', 'CB', 'RB'],
  CAR: ['TE', 'WR', 'OT', 'CB'],
  PIT: ['WR', 'OT', 'IOL', 'QB'],
  LAC: ['EDGE', 'IOL', 'DL', 'OT'],
  PHI: ['OT', 'EDGE', 'WR', 'TE'],
  CHI: ['DL', 'EDGE', 'S', 'IOL'],
  BUF: ['EDGE', 'WR', 'LB', 'DL'],
  SF:  ['OT', 'EDGE', 'WR', 'DL'],
  HOU: ['DL', 'OT', 'IOL', 'LB'],
  NE:  ['EDGE', 'OT', 'WR', 'LB'],
  SEA: ['CB', 'RB', 'EDGE', 'IOL'],
  IND: ['QB', 'OT', 'WR', 'LB'],
  JAX: ['QB', 'EDGE', 'WR', 'CB'],
  GB:  ['WR', 'CB', 'EDGE', 'S'],
  DEN: ['CB', 'WR', 'OT', 'EDGE'],
  ATL: ['QB', 'WR', 'OT', 'CB'],
};

const NFL_PROSPECTS = [
  { rank: 1,  name: 'Arvell Reese',         pos: 'LB',   school: 'Ohio State',      note: '' },
  { rank: 2,  name: 'Fernando Mendoza',     pos: 'QB',   school: 'Indiana',         note: '' },
  { rank: 3,  name: 'David Bailey',         pos: 'EDGE', school: 'Texas Tech',      note: '' },
  { rank: 4,  name: 'Jeremiyah Love',       pos: 'RB',   school: 'Notre Dame',      note: '' },
  { rank: 5,  name: 'Francis Mauigoa',      pos: 'OT',   school: 'Miami',           note: '' },
  { rank: 6,  name: 'Caleb Downs',          pos: 'S',    school: 'Ohio State',      note: '' },
  { rank: 7,  name: 'Sonny Styles',         pos: 'LB',   school: 'Ohio State',      note: '' },
  { rank: 8,  name: 'Mansoor Delane',       pos: 'CB',   school: 'LSU',             note: '' },
  { rank: 9,  name: 'Rueben Bain Jr.',      pos: 'EDGE', school: 'Miami',           note: '' },
  { rank: 10, name: 'Makai Lemon',          pos: 'WR',   school: 'USC',             note: '' },
  { rank: 11, name: 'Kenyon Sadiq',         pos: 'TE',   school: 'Oregon',          note: '' },
  { rank: 12, name: 'Jordyn Tyson',         pos: 'WR',   school: 'Arizona State',   note: '' },
  { rank: 13, name: 'Carnell Tate',         pos: 'WR',   school: 'Ohio State',      note: '' },
  { rank: 14, name: 'Monroe Freeling',      pos: 'OT',   school: 'Georgia',         note: '' },
  { rank: 15, name: 'Olaivavega Ioane',     pos: 'OG',   school: 'Penn State',      note: '' },
  { rank: 16, name: 'Jermod McCoy',         pos: 'CB',   school: 'Tennessee',       note: '' },
  { rank: 17, name: 'Kadyn Proctor',        pos: 'OT',   school: 'Alabama',         note: '' },
  { rank: 18, name: 'Akheem Mesidor',       pos: 'EDGE', school: 'Miami',           note: '' },
  { rank: 19, name: 'Spencer Fano',         pos: 'OT',   school: 'Utah',            note: '' },
  { rank: 20, name: 'Dillon Thieneman',     pos: 'S',    school: 'Oregon',          note: '' },
  { rank: 21, name: 'Emmanuel McNeil-Warren', pos: 'S',  school: 'Toledo',          note: '' },
  { rank: 22, name: 'Avieon Terrell',       pos: 'CB',   school: 'Clemson',         note: '' },
  { rank: 23, name: 'Denzel Boston',        pos: 'WR',   school: 'Washington',      note: '' },
  { rank: 24, name: 'Omar Cooper Jr.',      pos: 'WR',   school: 'Indiana',         note: '' },
  { rank: 25, name: 'Keldric Faulk',        pos: 'EDGE', school: 'Auburn',          note: '' },
  { rank: 26, name: 'Kayden McDonald',      pos: 'DT',   school: 'Ohio State',      note: '' },
  { rank: 27, name: 'Peter Woods',          pos: 'DT',   school: 'Clemson',         note: '' },
  { rank: 28, name: 'Caleb Lomu',           pos: 'OT',   school: 'Utah',            note: '' },
  { rank: 29, name: 'Zion Young',           pos: 'EDGE', school: 'Missouri',        note: '' },
  { rank: 30, name: 'Cashius Howell',       pos: 'EDGE', school: 'Texas A&M',       note: '' },
  { rank: 31, name: 'Colton Hood',          pos: 'CB',   school: 'Tennessee',       note: '' },
  { rank: 32, name: 'KC Concepcion',        pos: 'WR',   school: 'Texas A&M',       note: '' },
  { rank: 33, name: 'Chase Bisontis',       pos: 'OG',   school: 'Texas A&M',       note: '' },
  { rank: 34, name: 'Caleb Banks',          pos: 'DT',   school: 'Florida',         note: '' },
  { rank: 35, name: 'Anthony Hill Jr.',     pos: 'LB',   school: 'Texas',           note: '' },
  { rank: 36, name: 'Eli Stowers',          pos: 'TE',   school: 'Vanderbilt',      note: '' },
  { rank: 37, name: 'Ty Simpson',           pos: 'QB',   school: 'Alabama',         note: '' },
  { rank: 38, name: 'Brandon Cisse',        pos: 'CB',   school: 'South Carolina',  note: '' },
  { rank: 39, name: 'Chris Johnson',        pos: 'CB',   school: 'San Diego State', note: '' },
  { rank: 40, name: 'Zachariah Branch',     pos: 'WR',   school: 'Georgia',         note: '' },
  { rank: 41, name: 'Max Iheanachor',       pos: 'OT',   school: 'Arizona State',   note: '' },
  { rank: 42, name: 'Chris Brazzell II',    pos: 'WR',   school: 'Tennessee',       note: '' },
  { rank: 43, name: 'Germie Bernard',       pos: 'WR',   school: 'Alabama',         note: '' },
  { rank: 44, name: 'Gabe Jacas',           pos: 'EDGE', school: 'Illinois',        note: '' },
  { rank: 45, name: 'CJ Allen',             pos: 'LB',   school: 'Georgia',         note: '' },
  { rank: 46, name: 'Jacob Rodriguez',      pos: 'LB',   school: 'Texas Tech',      note: '' },
  { rank: 47, name: 'Emmanuel Pregnon',     pos: 'OG',   school: 'Oregon',          note: '' },
  { rank: 48, name: 'Keionte Scott',        pos: 'CB',   school: 'Miami',           note: '' },
  { rank: 49, name: 'Christen Miller',      pos: 'DT',   school: 'Georgia',         note: '' },
  { rank: 50, name: 'Jadarian Price',       pos: 'RB',   school: 'Notre Dame',      note: '' },
  { rank: 51,  name: 'Gennings Dunker',        pos: 'OT',   school: 'Iowa',            note: '' },
  { rank: 52,  name: 'Blake Miller',           pos: 'OT',   school: 'Clemson',         note: '' },
  { rank: 53,  name: 'T.J. Parker',            pos: 'EDGE', school: 'Clemson',         note: '' },
  { rank: 54,  name: 'Malachi Lawrence',       pos: 'EDGE', school: 'UCF',             note: '' },
  { rank: 55,  name: 'Jake Golday',            pos: 'LB',   school: 'Cincinnati',      note: '' },
  { rank: 56,  name: 'A.J. Haulcy',            pos: 'S',    school: 'LSU',             note: '' },
  { rank: 57,  name: 'Antonio Williams',       pos: 'WR',   school: 'Clemson',         note: '' },
  { rank: 58,  name: 'Keylan Rutledge',        pos: 'OG',   school: 'Georgia Tech',    note: '' },
  { rank: 59,  name: 'Malachi Fields',         pos: 'WR',   school: 'Notre Dame',      note: '' },
  { rank: 60,  name: 'Derrick Moore',          pos: 'EDGE', school: 'Michigan',        note: '' },
  { rank: 61,  name: 'R Mason Thomas',         pos: 'EDGE', school: 'Oklahoma',        note: '' },
  { rank: 62,  name: 'Josiah Trotter',         pos: 'LB',   school: 'Missouri',        note: '' },
  { rank: 63,  name: 'Zxavian Harris',         pos: 'DT',   school: 'Ole Miss',        note: '' },
  { rank: 64,  name: 'Max Klare',              pos: 'TE',   school: 'Ohio State',      note: '' },
  { rank: 65,  name: 'Malik Muhammad',         pos: 'CB',   school: 'Texas',           note: '' },
  { rank: 66,  name: 'D\'Angelo Ponds',        pos: 'CB',   school: 'Indiana',         note: '' },
  { rank: 67,  name: 'Lee Hunter',             pos: 'DT',   school: 'Texas Tech',      note: '' },
  { rank: 68,  name: 'Mike Washington Jr.',    pos: 'RB',   school: 'Arkansas',        note: '' },
  { rank: 69,  name: 'Treydan Stukes',         pos: 'S',    school: 'Arizona',         note: '' },
  { rank: 70,  name: 'Ted Hurst',              pos: 'WR',   school: 'Georgia State',   note: '' },
  { rank: 71,  name: 'Jalon Kilgore',          pos: 'S',    school: 'South Carolina',  note: '' },
  { rank: 72,  name: 'Skyler Bell',            pos: 'WR',   school: 'UConn',           note: '' },
  { rank: 73,  name: 'Elijah Sarratt',         pos: 'WR',   school: 'Indiana',         note: '' },
  { rank: 74,  name: 'Keyron Crawford',        pos: 'EDGE', school: 'Auburn',          note: '' },
  { rank: 75,  name: 'Keith Abney II',         pos: 'CB',   school: 'Arizona State',   note: '' },
  { rank: 76,  name: 'De\'Zhaun Stribling',    pos: 'WR',   school: 'Ole Miss',        note: '' },
  { rank: 77,  name: 'Chris Bell',             pos: 'WR',   school: 'Louisville',      note: '' },
  { rank: 78,  name: 'Domonique Orange',       pos: 'DT',   school: 'Iowa State',      note: '' },
  { rank: 79,  name: 'Jake Slaughter',         pos: 'C',    school: 'Florida',         note: '' },
  { rank: 80,  name: 'Sam Hecht',              pos: 'C',    school: 'Kansas State',    note: '' },
  { rank: 81,  name: 'Deion Burks',            pos: 'WR',   school: 'Oklahoma',        note: '' },
  { rank: 82,  name: 'Zakee Wheatley',         pos: 'S',    school: 'Penn State',      note: '' },
  { rank: 83,  name: 'Sam Roush',              pos: 'TE',   school: 'Stanford',        note: '' },
  { rank: 84,  name: 'Caleb Tiernan',          pos: 'OT',   school: 'Northwestern',    note: '' },
  { rank: 85,  name: 'Bud Clark',              pos: 'S',    school: 'TCU',             note: '' },
  { rank: 86,  name: 'Dametrious Crownover',   pos: 'OT',   school: 'Texas A&M',       note: '' },
  { rank: 87,  name: 'Garrett Nussmeier',      pos: 'QB',   school: 'LSU',             note: '' },
  { rank: 88,  name: 'Jaishawn Barham',        pos: 'EDGE', school: 'Michigan',        note: '' },
  { rank: 89,  name: 'Kyle Louis',             pos: 'LB',   school: 'Pittsburgh',      note: '' },
  { rank: 90,  name: 'Ja\'Kobi Lane',          pos: 'WR',   school: 'USC',             note: '' },
  { rank: 91,  name: 'Davison Igbinosun',      pos: 'CB',   school: 'Ohio State',      note: '' },
  { rank: 92,  name: 'Justin Joly',            pos: 'TE',   school: 'NC State',        note: '' },
  { rank: 93,  name: 'Gracen Halton',          pos: 'DT',   school: 'Oklahoma',        note: '' },
  { rank: 94,  name: 'Joshua Josephs',         pos: 'EDGE', school: 'Tennessee',       note: '' },
  { rank: 95,  name: 'Bryce Lance',            pos: 'WR',   school: 'North Dakota St', note: '' },
  { rank: 96,  name: 'Dani Dennis-Sutton',     pos: 'EDGE', school: 'Penn State',      note: '' },
  { rank: 97,  name: 'Genesis Smith',          pos: 'S',    school: 'Arizona',         note: '' },
  { rank: 98,  name: 'Kamari Ramsey',          pos: 'S',    school: 'USC',             note: '' },
  { rank: 99,  name: 'Logan Jones',            pos: 'C',    school: 'Iowa',            note: '' },
  { rank: 100, name: 'Romello Height',         pos: 'EDGE', school: 'Texas Tech',      note: '' },
  { rank: 101, name: 'LT Overton',             pos: 'EDGE', school: 'Alabama',         note: '' },
  { rank: 102, name: 'Brian Parker II',        pos: 'OG',   school: 'Duke',            note: '' },
  { rank: 103, name: 'Deontae Lawson',         pos: 'LB',   school: 'Alabama',         note: '' },
  { rank: 104, name: 'Connor Lew',             pos: 'C',    school: 'Auburn',          note: '' },
  { rank: 105, name: 'Will Lee III',           pos: 'CB',   school: 'Texas A&M',       note: '' },
  { rank: 106, name: 'Trey Zuhn III',          pos: 'C',    school: 'Texas A&M',       note: '' },
  { rank: 107, name: 'Harold Perkins Jr.',     pos: 'LB',   school: 'LSU',             note: '' },
  { rank: 108, name: 'Darrell Jackson Jr.',    pos: 'DT',   school: 'Florida State',   note: '' },
  { rank: 109, name: 'Chris McClellan',        pos: 'DT',   school: 'Missouri',        note: '' },
  { rank: 110, name: 'Oscar Delp',             pos: 'TE',   school: 'Georgia',         note: '' },
  { rank: 111, name: 'Tyler Onyedim',          pos: 'DT',   school: 'Texas A&M',       note: '' },
  { rank: 112, name: 'Daylen Everette',        pos: 'CB',   school: 'Georgia',         note: '' },
  { rank: 113, name: 'Carson Beck',            pos: 'QB',   school: 'Miami',           note: '' },
  { rank: 114, name: 'Anez Cooper',            pos: 'OG',   school: 'Miami',           note: '' },
  { rank: 115, name: 'Tacario Davis',          pos: 'CB',   school: 'Washington',      note: '' },
  { rank: 116, name: 'Drew Shelton',           pos: 'OT',   school: 'Penn State',      note: '' },
  { rank: 117, name: 'Jack Endries',           pos: 'TE',   school: 'Texas',           note: '' },
  { rank: 118, name: 'Eli Raridon',            pos: 'TE',   school: 'Notre Dame',      note: '' },
  { rank: 119, name: 'Devin Moore',            pos: 'CB',   school: 'Florida',         note: '' },
  { rank: 120, name: 'Austin Barber',          pos: 'OT',   school: 'Florida',         note: '' },
  { rank: 121, name: 'Nicholas Singleton',     pos: 'RB',   school: 'Penn State',      note: '' },
  { rank: 122, name: 'DeMonte Capehart',       pos: 'DT',   school: 'Clemson',         note: '' },
  { rank: 123, name: 'Jalen Farmer',           pos: 'OG',   school: 'Kentucky',        note: '' },
  { rank: 124, name: 'VJ Payne',               pos: 'S',    school: 'Kansas State',    note: '' },
  { rank: 125, name: 'Emmett Johnson',         pos: 'RB',   school: 'Nebraska',        note: '' },
  { rank: 126, name: 'Keagen Trost',           pos: 'OT',   school: 'Missouri',        note: '' },
  { rank: 127, name: 'Jadon Canady',           pos: 'S',    school: 'Oregon',          note: '' },
  { rank: 128, name: 'Chandler Rivers',        pos: 'CB',   school: 'Duke',            note: '' },
  { rank: 129, name: 'Drew Allar',             pos: 'QB',   school: 'Penn State',      note: '' },
  { rank: 130, name: 'Joe Royer',              pos: 'TE',   school: 'Cincinnati',      note: '' },
  { rank: 131, name: 'Jude Bowry',             pos: 'OT',   school: 'Boston College',  note: '' },
  { rank: 132, name: 'Rayshaun Benny',         pos: 'DT',   school: 'Michigan',        note: '' },
  { rank: 133, name: 'Demond Claiborne',       pos: 'RB',   school: 'Wake Forest',     note: '' },
  { rank: 134, name: 'Albert Regis',           pos: 'DT',   school: 'Texas A&M',       note: '' },
  { rank: 135, name: 'Adam Randall',           pos: 'RB',   school: 'Clemson',         note: '' },
  { rank: 136, name: 'J\'Mari Taylor',         pos: 'RB',   school: 'Virginia',        note: '' },
  { rank: 137, name: 'Billy Schrauth',         pos: 'OG',   school: 'Notre Dame',      note: '' },
  { rank: 138, name: 'Kevin Coleman Jr.',      pos: 'WR',   school: 'Missouri',        note: '' },
  { rank: 139, name: 'Kage Casey',             pos: 'OT',   school: 'Boise State',     note: '' },
  { rank: 140, name: 'Jeremiah Wright',        pos: 'OG',   school: 'Auburn',          note: '' },
  { rank: 141, name: 'Charles Demmings',       pos: 'CB',   school: 'SFA',             note: '' },
  { rank: 142, name: 'Jakobe Thomas',          pos: 'S',    school: 'Miami',           note: '' },
  { rank: 143, name: 'Le\'Veon Moss',          pos: 'RB',   school: 'Texas A&M',       note: '' },
  { rank: 144, name: 'Brenen Thompson',        pos: 'WR',   school: 'Mississippi St',  note: '' },
  { rank: 145, name: 'Jeff Caldwell',          pos: 'WR',   school: 'Cincinnati',      note: '' },
  { rank: 146, name: 'Kaytron Allen',          pos: 'RB',   school: 'Penn State',      note: '' },
  { rank: 147, name: 'Zane Durant',            pos: 'DT',   school: 'Penn State',      note: '' },
  { rank: 148, name: 'Michael Trigg',          pos: 'TE',   school: 'Baylor',          note: '' },
  { rank: 149, name: 'Kaleb Elarms-Orr',       pos: 'LB',   school: 'TCU',             note: '' },
  { rank: 150, name: 'Trey Moore',             pos: 'EDGE', school: 'Texas',           note: '' },
  { rank: 151, name: 'Bryce Boettcher',        pos: 'LB',   school: 'Oregon',          note: '' },
  { rank: 152, name: 'Taylen Green',           pos: 'QB',   school: 'Arkansas',        note: '' },
  { rank: 153, name: 'Cole Payton',            pos: 'QB',   school: 'North Dakota St', note: '' },
  { rank: 154, name: 'Josh Cuevas',            pos: 'TE',   school: 'Alabama',         note: '' },
  { rank: 155, name: 'Will Kacmarek',          pos: 'TE',   school: 'Ohio State',      note: '' },
  { rank: 156, name: 'Parker Brailsford',      pos: 'C',    school: 'Alabama',         note: '' },
  { rank: 157, name: 'Matt Gulbin',            pos: 'C',    school: 'Michigan State',  note: '' },
  { rank: 158, name: 'Ephesians Prysock',      pos: 'CB',   school: 'Washington',      note: '' },
  { rank: 159, name: 'Nate Boerkircher',       pos: 'TE',   school: 'Texas A&M',       note: '' },
  { rank: 160, name: 'Jimmy Rolder',           pos: 'LB',   school: 'Michigan',        note: '' },
  { rank: 161, name: 'Alex Harkey',            pos: 'OG',   school: 'Oregon',          note: '' },
  { rank: 162, name: 'Domani Jackson',         pos: 'CB',   school: 'Alabama',         note: '' },
  { rank: 163, name: 'Hezekiah Masses',        pos: 'CB',   school: 'California',      note: '' },
  { rank: 164, name: 'Caden Curry',            pos: 'EDGE', school: 'Ohio State',      note: '' },
  { rank: 165, name: 'Malik Benson',           pos: 'WR',   school: 'Oregon',          note: '' },
  { rank: 166, name: 'George Gumbs Jr.',       pos: 'EDGE', school: 'Florida',         note: '' },
  { rank: 167, name: 'Josh Cameron',           pos: 'WR',   school: 'Baylor',          note: '' },
  { rank: 168, name: 'Isaiah World',           pos: 'OT',   school: 'Oregon',          note: '' },
  { rank: 169, name: 'Julian Neal',            pos: 'CB',   school: 'Arkansas',        note: '' },
  { rank: 170, name: 'Robert Spears-Jennings', pos: 'S',    school: 'Oklahoma',        note: '' },
  { rank: 171, name: 'Bryson Eason',           pos: 'DT',   school: 'Tennessee',       note: '' },
  { rank: 172, name: 'Beau Stephens',          pos: 'OG',   school: 'Iowa',            note: '' },
  { rank: 173, name: 'Riley Nowakowski',       pos: 'TE',   school: 'Indiana',         note: '' },
  { rank: 174, name: 'Michael Taaffe',         pos: 'S',    school: 'Texas',           note: '' },
  { rank: 175, name: 'Jonah Coleman',          pos: 'RB',   school: 'Washington',      note: '' },
  { rank: 176, name: 'Marlin Klein',           pos: 'TE',   school: 'Michigan',        note: '' },
  { rank: 177, name: 'Colbie Young',           pos: 'WR',   school: 'Georgia',         note: '' },
  { rank: 178, name: 'Roman Hemby',            pos: 'RB',   school: 'Indiana',         note: '' },
  { rank: 179, name: 'Logan Fano',             pos: 'EDGE', school: 'Utah',            note: '' },
  { rank: 180, name: 'Matthew Hibner',         pos: 'TE',   school: 'SMU',             note: '' },
  { rank: 181, name: 'Justin Jefferson',       pos: 'LB',   school: 'Alabama',         note: '', espnId: 5150249 },
  { rank: 182, name: 'Seth McGowan',           pos: 'RB',   school: 'Kentucky',        note: '' },
  { rank: 183, name: 'Nick Barrett',           pos: 'DT',   school: 'South Carolina',  note: '' },
  { rank: 184, name: 'Cameron Ball',           pos: 'DT',   school: 'Arkansas',        note: '', espnId: 4691878 },
  { rank: 185, name: 'Travis Burke',           pos: 'OT',   school: 'Memphis',         note: '' },
  { rank: 186, name: 'Markel Bell',            pos: 'OT',   school: 'Miami',           note: '' },
  { rank: 187, name: 'Bishop Fitzgerald',      pos: 'S',    school: 'USC',             note: '' },
  { rank: 188, name: 'Fernando Carmona',       pos: 'OT',   school: 'Arkansas',        note: '' },
  { rank: 189, name: 'Toriano Pride Jr.',      pos: 'CB',   school: 'Missouri',        note: '' },
  { rank: 190, name: 'TJ Hall',                pos: 'CB',   school: 'Iowa',            note: '' },
  { rank: 191, name: 'Caleb Douglas',          pos: 'WR',   school: 'Texas Tech',      note: '' },
  { rank: 192, name: 'Pat Coogan',             pos: 'C',    school: 'Indiana',         note: '' },
  { rank: 193, name: 'J. Michael Sturdivant',  pos: 'WR',   school: 'Florida',         note: '' },
  { rank: 194, name: 'Diego Pounds',           pos: 'OT',   school: 'Ole Miss',        note: '' },
  { rank: 195, name: 'Lander Barton',          pos: 'LB',   school: 'Utah',            note: '' },
  { rank: 196, name: 'Taurean York',           pos: 'LB',   school: 'Texas A&M',       note: '' },
  { rank: 197, name: 'Aiden Fisher',           pos: 'LB',   school: 'Indiana',         note: '' },
  { rank: 198, name: 'Dae\'Quan Wright',       pos: 'TE',   school: 'Ole Miss',        note: '' },
  { rank: 199, name: 'Kendrick Law',           pos: 'WR',   school: 'Kentucky',        note: '' },
  { rank: 200, name: 'Cyrus Allen',            pos: 'WR',   school: 'Cincinnati',      note: '' },
  { rank: 201, name: 'Kaleb Proctor',            pos: 'DT',   school: 'SE Louisiana',      note: '' },
  { rank: 202, name: 'Brandon Cleveland',        pos: 'DT',   school: 'NC State',          note: '' },
  { rank: 203, name: 'Jam Miller',               pos: 'RB',   school: 'Alabama',           note: '' },
  { rank: 204, name: 'Mason Reiger',             pos: 'EDGE', school: 'Wisconsin',         note: '' },
  { rank: 205, name: 'Jack Kelly',               pos: 'LB',   school: 'BYU',               note: '' },
  { rank: 206, name: 'Carver Willis',            pos: 'OT',   school: 'Washington',        note: '' },
  { rank: 207, name: "Ar'maj Reed-Adams",        pos: 'OG',   school: 'Texas A&M',         note: '' },
  { rank: 208, name: 'Luke Altmyer',             pos: 'QB',   school: 'Illinois',          note: '' },
  { rank: 209, name: 'Harrison Wallace III',     pos: 'WR',   school: 'Ole Miss',          note: '' },
  { rank: 210, name: 'Tim Keenan III',           pos: 'DT',   school: 'Alabama',           note: '' },
  { rank: 211, name: 'Tanner Koziol',            pos: 'TE',   school: 'Ball State',        note: '' },
  { rank: 212, name: 'Reggie Virgil',            pos: 'WR',   school: 'Texas Tech',        note: '' },
  { rank: 213, name: 'Kaelon Black',             pos: 'RB',   school: 'Indiana',           note: '' },
  { rank: 214, name: 'Dontay Corleone',          pos: 'DT',   school: 'Cincinnati',        note: '' },
  { rank: 215, name: 'John Michael Gyllenborg',  pos: 'TE',   school: 'Wyoming',           note: '' },
  { rank: 216, name: 'Namdi Obiazor',            pos: 'LB',   school: 'TCU',               note: '' },
  { rank: 217, name: 'Eric Gentry',              pos: 'LB',   school: 'USC',               note: '' },
  { rank: 218, name: 'Logan Taylor',             pos: 'OG',   school: 'Boston College',    note: '' },
  { rank: 219, name: 'Behren Morton',            pos: 'QB',   school: 'Texas Tech',        note: '' },
  { rank: 220, name: 'Sawyer Robertson',         pos: 'QB',   school: 'Baylor',            note: '' },
  { rank: 221, name: 'Jaeden Roberts',           pos: 'OG',   school: 'Alabama',           note: '', espnId: 4431529 },
  { rank: 222, name: 'Zavion Thomas',            pos: 'WR',   school: 'LSU',               note: '' },
  { rank: 223, name: 'Scooby Williams',          pos: 'LB',   school: 'Texas A&M',         note: '' },
  { rank: 224, name: 'Dalton Johnson',           pos: 'S',    school: 'Arizona',           note: '' },
  { rank: 225, name: 'DJ Rogers',                pos: 'TE',   school: 'TCU',               note: '' },
  { rank: 226, name: 'Lorenzo Styles Jr.',       pos: 'S',    school: 'Ohio State',        note: '' },
  { rank: 227, name: 'Thaddeus Dixon',           pos: 'CB',   school: 'North Carolina',    note: '' },
  { rank: 228, name: 'Jalen Huskey',             pos: 'CB',   school: 'Maryland',          note: '' },
  { rank: 229, name: 'Kendal Daniels',           pos: 'LB',   school: 'Oklahoma',          note: '' },
  { rank: 230, name: 'Wesley Bissainthe',        pos: 'LB',   school: 'Miami',             note: '' },
  { rank: 231, name: 'DeShon Singleton',         pos: 'S',    school: 'Nebraska',          note: '' },
  { rank: 232, name: 'Cade Klubnik',             pos: 'QB',   school: 'Clemson',           note: '' },
  { rank: 233, name: 'Collin Wright',            pos: 'CB',   school: 'Stanford',          note: '' },
  { rank: 234, name: 'Dallen Bentley',           pos: 'TE',   school: 'Utah',              note: '' },
  { rank: 235, name: 'Wade Woodaz',              pos: 'LB',   school: 'Clemson',           note: '' },
  { rank: 236, name: 'Keyshaun Elliott',         pos: 'LB',   school: 'Arizona State',     note: '' },
  { rank: 237, name: 'Barion Brown',             pos: 'WR',   school: 'LSU',               note: '' },
  { rank: 238, name: 'Eric Rivers',              pos: 'WR',   school: 'Georgia Tech',      note: '' },
  { rank: 239, name: 'Eli Heidenreich',          pos: 'RB',   school: 'Navy',              note: '' },
  { rank: 240, name: 'Wesley Williams',          pos: 'EDGE', school: 'Duke',              note: '' },
  { rank: 241, name: 'Tyreak Sapp',              pos: 'EDGE', school: 'Florida',           note: '' },
  { rank: 242, name: 'Jager Burton',             pos: 'C',    school: 'Kentucky',          note: '' },
  { rank: 243, name: 'Joey Aguilar',             pos: 'QB',   school: 'App State',         note: '' },
  { rank: 244, name: 'Louis Moore',              pos: 'S',    school: 'Indiana',           note: '' },
  { rank: 245, name: 'Haynes King',              pos: 'QB',   school: 'Georgia Tech',      note: '' },
  { rank: 246, name: 'Patrick Payton',           pos: 'EDGE', school: 'LSU',               note: '' },
  { rank: 247, name: 'Quintayvious Hutchins',    pos: 'EDGE', school: 'Boston College',    note: '' },
  { rank: 248, name: 'David Gusta',              pos: 'DT',   school: 'Kentucky',          note: '' },
  { rank: 249, name: 'Dan Villari',              pos: 'TE',   school: 'Syracuse',          note: '' },
  { rank: 250, name: 'Brett Thorson',            pos: 'P',    school: 'Georgia',           note: '' },
  { rank: 251, name: 'Vincent Anthony Jr.',      pos: 'EDGE', school: 'Duke',              note: '' },
  { rank: 252, name: 'Kaden Wetjen',             pos: 'WR',   school: 'Iowa',              note: '' },
  { rank: 253, name: 'Febechi Nwaiwu',           pos: 'OG',   school: 'Oklahoma',          note: '' },
  { rank: 254, name: "Fa'alili Fa'amoe",         pos: 'OT',   school: 'Washington State',  note: '' },
  { rank: 255, name: 'Jack Pyburn',              pos: 'EDGE', school: 'LSU',               note: '' },
  { rank: 256, name: 'Evan Beerntsen',           pos: 'OG',   school: 'Northwestern',      note: '' },
  { rank: 257, name: 'Jacobian Guillory II',     pos: 'DT',   school: 'LSU',               note: '' },
  { rank: 258, name: 'Enrique Cruz Jr.',         pos: 'OT',   school: 'Kansas',            note: '' },
  { rank: 259, name: 'Aamil Wagner',             pos: 'OT',   school: 'Notre Dame',        note: '' },
  { rank: 260, name: 'CJ Daniels',               pos: 'WR',   school: 'LSU',               note: '' },
  { rank: 261, name: 'Trey Smack',               pos: 'K',   school: 'Florida',           note: '' },
  { rank: 262, name: 'Lake McRee',               pos: 'TE',   school: 'USC',               note: '' },
  { rank: 263, name: 'Skyler Gill-Howard',       pos: 'DT',   school: 'Texas Tech',        note: '' },
  { rank: 264, name: 'Joe Fagnano',              pos: 'QB',   school: 'UConn',             note: '' },
  { rank: 265, name: 'Red Murdock',              pos: 'LB',   school: 'Buffalo',           note: '' },
  { rank: 266, name: 'DJ Campbell',              pos: 'OG',   school: 'Texas',             note: '' },
  { rank: 267, name: 'Josh Moten',               pos: 'CB',   school: 'Southern Miss',     note: '' },
  { rank: 268, name: 'Anthony Lucas',            pos: 'EDGE', school: 'USC',               note: '' },
  { rank: 269, name: 'Robert Henry Jr.',         pos: 'RB',   school: 'UTSA',              note: '' },
  { rank: 270, name: 'Bauer Sharp',              pos: 'TE',   school: 'Oklahoma',          note: '' },
  { rank: 271, name: 'RJ Maryland',              pos: 'TE',   school: 'SMU',               note: '' },
  { rank: 272, name: 'Diego Pavia',              pos: 'QB',   school: 'Vanderbilt',        note: '' },
  { rank: 273, name: 'Marvin Jones Jr.',         pos: 'EDGE', school: 'Florida State',     note: '', espnId: 4685425 },
  { rank: 274, name: 'Emmanuel Henderson Jr.',   pos: 'WR',   school: 'Kansas',            note: '' },
  { rank: 275, name: 'Dillon Bell',              pos: 'WR',   school: 'Georgia',           note: '' },
  { rank: 276, name: 'Eric McAlister',           pos: 'WR',   school: 'TCU',               note: '' },
  { rank: 277, name: 'Rahsul Faison',            pos: 'RB',   school: 'South Carolina',    note: '' },
  { rank: 278, name: 'Nadame Tucker',            pos: 'EDGE', school: 'Western Michigan',   note: '' },
  { rank: 279, name: 'Aaron Anderson',           pos: 'WR',   school: 'LSU',               note: '' },
  { rank: 280, name: 'Damonic Williams',         pos: 'DT',   school: 'Oklahoma',          note: '' },
  { rank: 281, name: 'Max Bredeson',             pos: 'TE',   school: 'Michigan',          note: '' },
  { rank: 282, name: 'Jaren Kanak',              pos: 'TE',   school: 'Oklahoma',          note: '' },
  { rank: 283, name: 'Jalon Daniels',            pos: 'QB',   school: 'Kansas',            note: '' },
  { rank: 284, name: 'Max Llewellyn',            pos: 'EDGE', school: 'Iowa',              note: '', espnId: 4683101 },
  { rank: 285, name: 'Tyren Montgomery',         pos: 'WR',   school: 'John Carroll',      note: '', espnId: 5103197 },
  { rank: 286, name: 'Jordan Hudson',            pos: 'WR',   school: 'SMU',               note: '' },
  { rank: 287, name: 'Aidan Hubbard',            pos: 'EDGE', school: 'Northwestern',      note: '' },
  { rank: 288, name: 'Khalil Dinkins',           pos: 'TE',   school: 'Penn State',        note: '' },
  { rank: 289, name: 'Skyler Thomas',            pos: 'S',    school: 'Oregon State',      note: '' },
  { rank: 290, name: 'Chris Hilton Jr.',         pos: 'WR',   school: 'LSU',               note: '' },
  { rank: 291, name: 'Caullin Lacy',             pos: 'WR',   school: 'Louisville',        note: '' },
  { rank: 292, name: 'Miles Kitselman',          pos: 'TE',   school: 'Tennessee',         note: '' },
  { rank: 293, name: 'Karson Sharar',            pos: 'LB',   school: 'Iowa',              note: '' },
  { rank: 294, name: 'Latrell McCutchin Sr.',    pos: 'CB',   school: 'Houston',           note: '' },
  { rank: 295, name: 'Jackie Marshall',          pos: 'DT',   school: 'Baylor',            note: '' },
  { rank: 296, name: 'Kam Dewberry',             pos: 'OG',   school: 'Texas A&M',         note: '' },
  { rank: 297, name: 'Ahmari Harvey',            pos: 'CB',   school: 'Georgia Tech',      note: '' },
  { rank: 298, name: 'Jordan van den Berg',      pos: 'DT',   school: 'Georgia Tech',      note: '' },
  { rank: 299, name: 'J.C. Davis',               pos: 'OT',   school: 'Illinois',          note: '' },
  { rank: 300, name: 'Xavier Nwankpa',           pos: 'S',    school: 'Iowa',              note: '' },
  { rank: 712, name: 'Rece Verhoff',             pos: 'K',    school: 'North Carolina',    note: '' },
];

const NFL_TEAM_ARCHETYPES = {
  ARI: { style: 'safe',   scheme: '3-4', preferredPos: ['OT', 'EDGE', 'QB', 'LB'] },
  ATL: { style: 'bpa',    scheme: '3-4', preferredPos: ['WR', 'DL', 'CB', 'OT'] },
  BAL: { style: 'bpa',    scheme: '3-4', preferredPos: ['IOL', 'WR', 'TE', 'OT'] },
  BUF: { style: 'traits', scheme: '4-3', preferredPos: ['EDGE', 'WR', 'LB', 'DL'] },
  CAR: { style: 'needs',  scheme: '3-4', preferredPos: ['TE', 'WR', 'OT', 'S'] },
  CHI: { style: 'traits', scheme: '4-3', preferredPos: ['EDGE', 'DL', 'S', 'OT'] },
  CIN: { style: 'bpa',    scheme: '4-3', preferredPos: ['CB', 'S', 'EDGE', 'LB'] },
  CLE: { style: 'traits', scheme: '4-3', preferredPos: ['WR', 'OT', 'CB', 'EDGE'] },
  DAL: { style: 'bpa',    scheme: '4-3', preferredPos: ['CB', 'EDGE', 'LB', 'S'] },
  DEN: { style: 'safe',   scheme: '3-4', preferredPos: ['TE', 'LB', 'DL', 'RB'] },
  DET: { style: 'traits', scheme: '4-3', preferredPos: ['OT', 'EDGE', 'DL', 'IOL'] },
  GB:  { style: 'traits', scheme: '4-3', preferredPos: ['CB', 'DL', 'EDGE', 'LB'] },
  HOU: { style: 'bpa',    scheme: '4-3', preferredPos: ['DL', 'OT', 'IOL', 'LB'] },
  IND: { style: 'traits', scheme: '4-3', preferredPos: ['LB', 'EDGE', 'WR', 'OT'] },
  JAX: { style: 'needs',  scheme: '3-4', preferredPos: ['LB', 'DL', 'S', 'RB'] },
  KC:  { style: 'bpa',    scheme: '4-3', preferredPos: ['CB', 'EDGE', 'WR', 'OT'] },
  LV:  { style: 'traits', scheme: '4-3', preferredPos: ['QB', 'WR', 'OT', 'DL'] },
  LAC: { style: 'safe',   scheme: '3-4', preferredPos: ['EDGE', 'IOL', 'DL', 'OT'] },
  LAR: { style: 'traits', scheme: '3-4', preferredPos: ['WR', 'OT', 'CB', 'LB'] },
  MIA: { style: 'traits', scheme: '3-4', preferredPos: ['WR', 'CB', 'OT', 'EDGE'] },
  MIN: { style: 'bpa',    scheme: '3-4', preferredPos: ['S', 'CB', 'DL', 'RB'] },
  NE:  { style: 'safe',   scheme: '3-4', preferredPos: ['EDGE', 'OT', 'WR', 'LB'] },
  NO:  { style: 'needs',  scheme: '4-3', preferredPos: ['WR', 'EDGE', 'CB', 'LB'] },
  NYG: { style: 'traits', scheme: '3-4', preferredPos: ['LB', 'S', 'WR', 'OT'] },
  NYJ: { style: 'safe',   scheme: '3-4', preferredPos: ['LB', 'WR', 'EDGE', 'CB'] },
  PHI: { style: 'traits', scheme: '3-4', preferredPos: ['OT', 'EDGE', 'WR', 'TE'] },
  PIT: { style: 'safe',   scheme: '3-4', preferredPos: ['WR', 'OT', 'IOL', 'QB'] },
  SF:  { style: 'bpa',    scheme: '4-3', preferredPos: ['OT', 'EDGE', 'WR', 'CB'] },
  SEA: { style: 'traits', scheme: '3-4', preferredPos: ['CB', 'RB', 'EDGE', 'IOL'] },
  TB:  { style: 'bpa',    scheme: '3-4', preferredPos: ['EDGE', 'TE', 'LB', 'CB'] },
  TEN: { style: 'traits', scheme: '4-3', preferredPos: ['RB', 'EDGE', 'LB', 'WR'] },
  WAS: { style: 'bpa',    scheme: '4-3', preferredPos: ['WR', 'EDGE', 'S', 'RB'] }
};

const NFL_DRAFT_LOCKS = [
  { pick: 1, team: 'LV', prospectName: 'Fernando Mendoza', probability: 1.0 },
  { pick: 2, team: 'NYJ', prospectName: 'Arvell Reese', probability: 0.90 },
  // add any others you're confident about
];