const COLLEGE_TEAMS = {
  'Georgia':       { color: '#BA0C2F', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png' },
  'Michigan':      { color: '#00274C', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png' },
  'Ohio State':    { color: '#BB0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png' },
  'Alabama':       { color: '#9E1B32', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png' },
  'Notre Dame':    { color: '#0C2340', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png' },
  'Texas Tech':    { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png' },
  'Tennessee':     { color: '#FF8200', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png' },
  'Illinois':      { color: '#E84A27', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png' },
  'Arizona State': { color: '#8C1D40', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png' },
  'San Diego State': { color: '#A6192E', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png' },
  'South Carolina': { color: '#73000a', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png' },
  'Miami':         { color: '#F47321', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png' },
  'Indiana':       { color: '#990000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png' },
  'LSU':           { color: '#461D7C', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png' },
  'USC':           { color: '#990000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png' },
  'Oregon':        { color: '#124734', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png' },
  'Penn State':    { color: '#041E42', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png' },
  'Utah':          { color: '#CC0000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png' },
  'Toledo':        { color: '#154733', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png' },
  'Clemson':       { color: '#F56600', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png' },
  'Washington':    { color: '#4B2E83', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png' },
  'Auburn':        { color: '#0C2340', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png' },
  'Missouri':      { color: '#2C2A29', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png' },
  'Texas A&M':     { color: '#500000', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png' },
  'Florida':       { color: '#0021A5', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png' },
  'Texas':         { color: '#BF5700', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png' },
  'Vanderbilt':    { color: '#866D4B', logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png' },
};

const NFL_TEAMS = {
  TEN: { name: 'Tennessee Titans',       abbr: 'TEN', color: '#4B92DB' },
  CLE: { name: 'Cleveland Browns',       abbr: 'CLE', color: '#FF3C00' },
  NYG: { name: 'New York Giants',        abbr: 'NYG', color: '#0B2265' },
  NE:  { name: 'New England Patriots',   abbr: 'NE',  color: '#002244' },
  JAX: { name: 'Jacksonville Jaguars',   abbr: 'JAX', color: '#006778' },
  LV:  { name: 'Las Vegas Raiders',      abbr: 'LV',  color: '#A5ACAF' },
  NYJ: { name: 'New York Jets',          abbr: 'NYJ', color: '#125740' },
  CAR: { name: 'Carolina Panthers',      abbr: 'CAR', color: '#0085CA' },
  NO:  { name: 'New Orleans Saints',     abbr: 'NO',  color: '#D3BC8D' },
  CHI: { name: 'Chicago Bears',          abbr: 'CHI', color: '#0B162A' },
  SF:  { name: 'San Francisco 49ers',    abbr: 'SF',  color: '#AA0000' },
  DAL: { name: 'Dallas Cowboys',         abbr: 'DAL', color: '#003594' },
  MIA: { name: 'Miami Dolphins',         abbr: 'MIA', color: '#008E97' },
  IND: { name: 'Indianapolis Colts',     abbr: 'IND', color: '#002C5F' },
  ATL: { name: 'Atlanta Falcons',        abbr: 'ATL', color: '#A71930' },
  ARI: { name: 'Arizona Cardinals',      abbr: 'ARI', color: '#97233F' },
  CIN: { name: 'Cincinnati Bengals',     abbr: 'CIN', color: '#FB4F14' },
  SEA: { name: 'Seattle Seahawks',       abbr: 'SEA', color: '#002244' },
  TB:  { name: 'Tampa Bay Buccaneers',   abbr: 'TB',  color: '#D50A0A' },
  DEN: { name: 'Denver Broncos',         abbr: 'DEN', color: '#FB4F14' },
  PIT: { name: 'Pittsburgh Steelers',    abbr: 'PIT', color: '#FFB612' },
  LAC: { name: 'Los Angeles Chargers',   abbr: 'LAC', color: '#0080C6' },
  GB:  { name: 'Green Bay Packers',      abbr: 'GB',  color: '#203731' },
  MIN: { name: 'Minnesota Vikings',      abbr: 'MIN', color: '#4F2683' },
  HOU: { name: 'Houston Texans',         abbr: 'HOU', color: '#03202F' },
  LAR: { name: 'Los Angeles Rams',       abbr: 'LAR', color: '#003594' },
  BAL: { name: 'Baltimore Ravens',       abbr: 'BAL', color: '#241773' },
  WAS: { name: 'Washington Commanders',  abbr: 'WAS', color: '#5A1414' },
  DET: { name: 'Detroit Lions',          abbr: 'DET', color: '#0076B6' },
  BUF: { name: 'Buffalo Bills',          abbr: 'BUF', color: '#00338D' },
  PHI: { name: 'Philadelphia Eagles',    abbr: 'PHI', color: '#004C54' },
  KC:  { name: 'Kansas City Chiefs',     abbr: 'KC',  color: '#E31837' },
};

const NFL_DRAFT_ORDER = [
  { pick: 1,  team: 'LV',  needs: ['QB', 'WR', 'OT', 'DL'], note: 'Raiders on the clock for Mendoza?' },
  { pick: 2,  team: 'NYJ', needs: ['LB', 'WR', 'EDGE', 'CB'], note: '' },
  { pick: 3,  team: 'ARI', needs: ['OT', 'EDGE', 'QB', 'LB'], note: 'Kyler Murray departed this offseason' },
  { pick: 4,  team: 'TEN', needs: ['RB', 'EDGE', 'LB', 'WR'], note: 'Protecting Cam Ward is priority #1' },
  { pick: 5,  team: 'NYG', needs: ['LB', 'S', 'WR', 'RB'], note: 'Dexter Lawrence trade rumors looming' },
  { pick: 6,  team: 'CLE', needs: ['WR', 'OT', 'CB', 'EDGE'], note: '' },
  { pick: 7,  team: 'WAS', needs: ['EDGE', 'S', 'WR', 'RB'], note: '' },
  { pick: 8,  team: 'NO',  needs: ['WR', 'EDGE', 'CB', 'LB'], note: '' },
  { pick: 9,  team: 'KC',  needs: ['CB', 'EDGE', 'WR', 'OT'], note: 'Rare top-10 pick for the Chiefs' },
  { pick: 10, team: 'CIN', needs: ['CB', 'S', 'EDGE', 'LB'], note: 'Defense struggled to get off the field' },
  { pick: 11, team: 'MIA', needs: ['CB', 'WR', 'OT', 'EDGE'], note: 'Tua Tagovailoa departed in FA' },
  { pick: 12, team: 'DAL', needs: ['CB', 'EDGE', 'LB', 'S'], note: 'Post-Micah Parsons era begins' },
  { pick: 13, team: 'LAR', needs: ['WR', 'OT', 'LB', 'CB'], note: 'via ATL' },
  { pick: 14, team: 'BAL', needs: ['IOL', 'WR', 'TE', 'OT'], note: '' },
  { pick: 15, team: 'TB',  needs: ['EDGE', 'TE', 'LB', 'CB'], note: '' },
  { pick: 16, team: 'NYJ', needs: ['LB', 'WR', 'EDGE', 'CB'], note: 'via IND' },
  { pick: 17, team: 'DET', needs: ['OT', 'EDGE', 'DL', 'CB'], note: '' },
  { pick: 18, team: 'MIN', needs: ['S', 'DL', 'CB', 'RB'], note: '' },
  { pick: 19, team: 'CAR', needs: ['TE', 'WR', 'OT', 'CB'], note: '' },
  { pick: 20, team: 'DAL', needs: ['CB', 'EDGE', 'LB', 'S'], note: 'via GB' },
  { pick: 21, team: 'PIT', needs: ['WR', 'OT', 'IOL', 'QB'], note: 'Drafting in their home city' },
  { pick: 22, team: 'LAC', needs: ['EDGE', 'IOL', 'DL', 'OT'], note: '' },
  { pick: 23, team: 'PHI', needs: ['OT', 'EDGE', 'WR', 'TE'], note: '' },
  { pick: 24, team: 'CLE', needs: ['WR', 'OT', 'CB', 'EDGE'], note: 'via JAX' },
  { pick: 25, team: 'CHI', needs: ['DL', 'EDGE', 'S', 'IOL'], note: '' },
  { pick: 26, team: 'BUF', needs: ['EDGE', 'WR', 'LB', 'DL'], note: '' },
  { pick: 27, team: 'SF',  needs: ['OT', 'EDGE', 'WR', 'DL'], note: '' },
  { pick: 28, team: 'HOU', needs: ['DL', 'OT', 'IOL', 'LB'], note: '' },
  { pick: 29, team: 'KC',  needs: ['CB', 'EDGE', 'WR', 'OT'], note: 'via LAR' },
  { pick: 30, team: 'MIA', needs: ['CB', 'WR', 'OT', 'EDGE'], note: 'via DEN' },
  { pick: 31, team: 'NE',  needs: ['EDGE', 'OT', 'WR', 'LB'], note: '' },
  { pick: 32, team: 'SEA', needs: ['CB', 'RB', 'EDGE', 'IOL'], note: '' },
];

const NFL_PROSPECTS = [
  { rank: 1,  name: 'Arvell Reese',         pos: 'LB',   school: 'Ohio State',      grade: 95, note: '' },
  { rank: 2,  name: 'Fernando Mendoza',     pos: 'QB',   school: 'Indiana',         grade: 94, note: '' },
  { rank: 3,  name: 'David Bailey',         pos: 'EDGE', school: 'Texas Tech',      grade: 93, note: '' },
  { rank: 4,  name: 'Jeremiyah Love',       pos: 'RB',   school: 'Notre Dame',      grade: 92, note: '' },
  { rank: 5,  name: 'Francis Mauigoa',      pos: 'OT',   school: 'Miami',           grade: 91, note: '' },
  { rank: 6,  name: 'Caleb Downs',          pos: 'S',    school: 'Ohio State',      grade: 90, note: '' },
  { rank: 7,  name: 'Sonny Styles',         pos: 'LB',   school: 'Ohio State',      grade: 89, note: '' },
  { rank: 8,  name: 'Mansoor Delane',       pos: 'CB',   school: 'LSU',             grade: 88, note: '' },
  { rank: 9,  name: 'Rueben Bain Jr.',      pos: 'EDGE', school: 'Miami',           grade: 87, note: '' },
  { rank: 10, name: 'Makai Lemon',          pos: 'WR',   school: 'USC',             grade: 86, note: '' },
  { rank: 11, name: 'Kenyon Sadiq',         pos: 'TE',   school: 'Oregon',          grade: 85, note: '' },
  { rank: 12, name: 'Jordyn Tyson',         pos: 'WR',   school: 'Arizona State',   grade: 84, note: '' },
  { rank: 13, name: 'Carnell Tate',         pos: 'WR',   school: 'Ohio State',      grade: 83, note: '' },
  { rank: 14, name: 'Monroe Freeling',      pos: 'OT',   school: 'Georgia',         grade: 82, note: '' },
  { rank: 15, name: 'Olaivavega Ioane',     pos: 'OG',   school: 'Penn State',      grade: 81, note: '' },
  { rank: 16, name: 'Jermod McCoy',         pos: 'CB',   school: 'Tennessee',       grade: 80, note: '' },
  { rank: 17, name: 'Kadyn Proctor',        pos: 'OT',   school: 'Alabama',         grade: 79, note: '' },
  { rank: 18, name: 'Akheem Mesidor',       pos: 'EDGE', school: 'Miami',           grade: 78, note: '' },
  { rank: 19, name: 'Spencer Fano',         pos: 'OT',   school: 'Utah',            grade: 77, note: '' },
  { rank: 20, name: 'Dillon Thieneman',     pos: 'S',    school: 'Oregon',          grade: 76, note: '' },
  { rank: 21, name: 'Emmanuel McNeil-Warren', pos: 'S',   school: 'Toledo',         grade: 75, note: '' },
  { rank: 22, name: 'Avieon Terrell',       pos: 'CB',   school: 'Clemson',         grade: 74, note: '' },
  { rank: 23, name: 'Denzel Boston',        pos: 'WR',   school: 'Washington',      grade: 73, note: '' },
  { rank: 24, name: 'Omar Cooper Jr.',      pos: 'WR',   school: 'Indiana',         grade: 72, note: '' },
  { rank: 25, name: 'Keldric Faulk',        pos: 'EDGE', school: 'Auburn',          grade: 71, note: '' },
  { rank: 26, name: 'Kayden McDonald',      pos: 'DT',   school: 'Ohio State',      grade: 70, note: '' },
  { rank: 27, name: 'Peter Woods',          pos: 'DT',   school: 'Clemson',         grade: 69, note: '' },
  { rank: 28, name: 'Caleb Lomu',           pos: 'OT',   school: 'Utah',            grade: 68, note: '' },
  { rank: 29, name: 'Zion Young',           pos: 'EDGE', school: 'Missouri',        grade: 67, note: '' },
  { rank: 30, name: 'Cashius Howell',       pos: 'EDGE', school: 'Texas A&M',       grade: 66, note: '' },
  { rank: 31, name: 'Colton Hood',          pos: 'CB',   school: 'Tennessee',       grade: 65, note: '' },
  { rank: 32, name: 'KC Concepcion',        pos: 'WR',   school: 'Texas A&M',       grade: 64, note: '' },
  { rank: 33, name: 'Chase Bisontis',       pos: 'OG',   school: 'Texas A&M',       grade: 63, note: '' },
  { rank: 34, name: 'Caleb Banks',          pos: 'DT',   school: 'Florida',         grade: 62, note: '' },
  { rank: 35, name: 'Anthony Hill Jr.',     pos: 'LB',   school: 'Texas',           grade: 61, note: '' },
  { rank: 36, name: 'Eli Stowers',          pos: 'TE',   school: 'Vanderbilt',      grade: 60, note: '' },
  { rank: 37, name: 'Ty Simpson',           pos: 'QB',   school: 'Alabama',         grade: 59, note: '' },
  { rank: 38, name: 'Brandon Cisse',        pos: 'CB',   school: 'South Carolina',  grade: 58, note: '' },
  { rank: 39, name: 'Chris Johnson',        pos: 'CB',   school: 'San Diego State', grade: 57, note: '' },
  { rank: 40, name: 'Zachariah Branch',     pos: 'WR',   school: 'Georgia',         grade: 56, note: '' },
  { rank: 41, name: 'Max Iheanachor',       pos: 'OT',   school: 'Arizona State',   grade: 55, note: '' },
  { rank: 42, name: 'Chris Brazzell II',    pos: 'WR',   school: 'Tennessee',       grade: 54, note: '' },
  { rank: 43, name: 'Germie Bernard',       pos: 'WR',   school: 'Alabama',         grade: 53, note: '' },
  { rank: 44, name: 'Gabe Jacas',           pos: 'EDGE', school: 'Illinois',        grade: 52, note: '' },
  { rank: 45, name: 'CJ Allen',             pos: 'LB',   school: 'Georgia',         grade: 51, note: '' },
  { rank: 46, name: 'Jacob Rodriguez',      pos: 'LB',   school: 'Texas Tech',      grade: 50, note: '' },
  { rank: 47, name: 'Emmanuel Pregnon',     pos: 'OG',   school: 'Oregon',          grade: 49, note: '' },
  { rank: 48, name: 'Keionte Scott',        pos: 'CB',   school: 'Miami',           grade: 48, note: '' },
  { rank: 49, name: 'Christen Miller',      pos: 'DT',   school: 'Georgia',         grade: 47, note: '' },
  { rank: 50, name: 'Jadarian Price',       pos: 'RB',   school: 'Notre Dame',      grade: 46, note: '' },
];